/**************************************************************************************************
 * project
 * Description - Sys9806 - Site Running Test
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sys.sysItSupport.sysSiteRunningTest;

import zebra.data.ParamEntity;

public interface SysSiteRunningTestBiz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity doSearch(ParamEntity paramEntity) throws Exception;
}