<%/************************************************************************************************
* Description - Sys9802 - Assignment
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet requestDataSet = (DataSet)paramEntity.getRequestDataSet();
	DataSet prtSetup = (DataSet)paramEntity.getObject("prtSetup");
	String mode = requestDataSet.getValue("mode");
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconPerci.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
var mode = "<%=mode%>";
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divPopupWindowHolder">
<div id="divFixedPanelPopup">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerPopup">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnUnlock" caption="sys9802.button.unlock" iconClass="fa-unlock-alt"/>
			<ui:button id="btnClose" caption="button.com.close" iconClass="fa-times"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea"></div>
<div id="divInformArea"></div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelPopup">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerPopup">
	<table id="tblGrid" class="tblGrid sort autosort">
		<colgroup>
				<col width="2%"/>
				<col width="*"/>
				<col width="11%"/>
				<col width="12%"/>
				<col width="12%"/>
				<col width="13%"/>
				<col width="11%"/>
				<col width="8%"/>
				<col width="9%"/>
				<col width="7%"/>
			</colgroup>
		<thead id="tblGridHead">
			<tr>
				<th class="thGrid"><ui:icon id="icnRdo" className="fa-dot-circle-o fa-lg" status="display"/></th>
				<th class="thGrid">PRT_ASSIGNMENT_SETUP_ID</th>
				<th class="thGrid">ASSIGNMENT_ID</th>
				<th class="thGrid">PRT_ORGANISATION_ID</th>
				<th class="thGrid">PRT_DOCUMENT_ID</th>
				<th class="thGrid">PRT_COH_SCENARIO_ID</th>
				<th class="thGrid">PRT_WORKING_STATE</th>
				<th class="thGrid">CREATED_BY</th>
				<th class="thGrid">CREATION_DATE</th>
				<th class="thGrid">IS_ACTIVE</th>
			</tr>
		</thead>
		<tbody id="tblGridBody">
<%
		if (prtSetup.getRowCnt() > 0) {
			for (int i=0; i<prtSetup.getRowCnt(); i++) {
%>
			<tr>
				<td class="tdGrid Ct"><input type="radio" id="" name="rdoForAction" class="rdoEn inTblGrid" value="<%=prtSetup.getValue(i, "ASSIGNMENT_ID")%>"/></td>
				<td class="tdGrid Ct"><%=prtSetup.getValue(i, "PRT_ASSIGNMENT_SETUP_ID")%></td>
				<td class="tdGrid Ct"><%=prtSetup.getValue(i, "ASSIGNMENT_ID")%></td>
				<td class="tdGrid Ct"><%=prtSetup.getValue(i, "PRT_ORGANISATION_ID")%></td>
				<td class="tdGrid Ct"><%=prtSetup.getValue(i, "PRT_DOCUMENT_ID")%></td>
				<td class="tdGrid Ct"><%=prtSetup.getValue(i, "PRT_COH_SCENARIO_ID")%></td>
				<td class="tdGrid Ct"><%=prtSetup.getValue(i, "PRT_WORKING_STATE")%></td>
				<td class="tdGrid Ct"><%=prtSetup.getValue(i, "CREATED_BY")%></td>
				<td class="tdGrid Ct"><%=prtSetup.getValue(i, "CREATION_DATE")%></td>
				<td class="tdGrid Ct"><%=prtSetup.getValue(i, "IS_ACTIVE")%></td>
			</tr>
<%
			}
		} else {
%>
			<tr>
				<td class="tdGrid Ct" colspan="10"><mc:msg key="I001"/></td>
			</tr>
<%
		}
%>
		</tbody>
	</table>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>