<%/************************************************************************************************
* Description - Sys9802 - Assignment
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet requestDataSet = (DataSet)paramEntity.getRequestDataSet();
	HpAssignmentsD assignment = (HpAssignmentsD)paramEntity.getObject("assignment");
	String mode = requestDataSet.getValue("mode");
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconPerci.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
var mode = "<%=mode%>";
var assignmentId = "<%=requestDataSet.getValue("assignmentId")%>";
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divPopupWindowHolder">
<div id="divFixedPanelPopup">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerPopup">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnEdit" caption="button.com.edit" iconClass="fa-edit"/>
			<ui:button id="btnClose" caption="button.com.close" iconClass="fa-times"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea"></div>
<div id="divInformArea" class="areaContainerPopup">
	<table class="tblInform">
		<caption class="captionInform"><mc:msg key="sys9802.caption.asgInfo"/></caption>
		<colgroup>
			<col width="18%"/>
			<col width="20%"/>
			<col width="25%"/>
			<col width="*"/>
		</colgroup>
		<tr>
			<th class="thInform Rt"><mc:msg key="sys9802.header.asgId"/></th>
			<td class="tdInform"><%=CommonUtil.getNumberMask(assignment.getAssignmentId(), "####")%></td>
			<th class="thInform Rt"><mc:msg key="sys9802.header.asgNumber"/></th>
			<td class="tdInform"><%=assignment.getAssignmentNumber()%></td>
		</tr>
	</table>
</div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelPopup">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerPopup">
	<table class="tblEdit withPadding">
		<caption class="captionDefault"><mc:msg key="sys9802.header.workingState"/></caption>
		<colgroup>
			<col width="50%"/>
			<col width="50%"/>
		</colgroup>
		<tr>
			<th class="thEdit Ct"><mc:msg key="sys9802.header.from"/></th>
			<th class="thEdit Ct"><mc:msg key="sys9802.header.to"/></th>
		</tr>
		<tr>
			<td class="tdEdit Ct"><ui:text name="workingStateFrom" value="<%=assignment.getWorkingState()%>" className="Ct" status="display"/></td>
			<td class="tdEdit Ct"><ui:ccselect name="workingStateTo" codeType="STATES"/></td>
		</tr>
	</table>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>