<%/************************************************************************************************
* Description - sys9804 - Invoice
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet requestDataSet = (DataSet)paramEntity.getRequestDataSet();
	DataSet invoice = (DataSet)paramEntity.getObject("invoice");
	String mode = requestDataSet.getValue("mode");
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconPerci.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
var mode = "<%=mode%>";
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divPopupWindowHolder">
<div id="divFixedPanelPopup">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerPopup">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnSave" caption="button.com.save" iconClass="fa-save"/>
			<ui:button id="btnClose" caption="button.com.close" iconClass="fa-times"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea"></div>
<div id="divInformArea" class="areaContainerPopup">
	<table class="tblInform">
		<colgroup>
			<col width="12%"/>
			<col width="*"/>
		</colgroup>
		<tr>
			<th class="thInform Rt">Update Invoice Status To</th>
			<td class="tdInform"><ui:ccselect name="statusTo" codeType="INVOICE_STATUS"/></td>
		</tr>
	</table>
</div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelPopup">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerPopup">
	<table id="tblGrid" class="tblGrid sort autosort">
		<colgroup>
			<col width="2%"/>
			<col width="6%"/>
			<col width="10%"/>
			<col width="9%"/>
			<col width="7%"/>
			<col width="7%"/>
			<col width="7%"/>
			<col width="6%"/>
			<col width="9%"/>
			<col width="*"/>
			<col width="7%"/>
			<col width="7%"/>
		</colgroup>
		<thead id="tblGridHead">
			<tr>
				<th class="thGrid"><ui:icon id="icnCheck" useFor="checkGrid"/></th>
				<th class="thGrid">Invoice Id</th>
				<th class="thGrid">Invoice Number</th>
				<th class="thGrid">Group Invoice Id</th>
				<th class="thGrid">Invoice Date</th>
				<th class="thGrid">Invoice Amount</th>
				<th class="thGrid">GST Amount</th>
				<th class="thGrid">Total</th>
				<th class="thGrid">Status</th>
				<th class="thGrid">Invoice To</th>
				<th class="thGrid">Period Start</th>
				<th class="thGrid">Period End</th>
			</tr>
		</thead>
		<tbody id="tblGridBody">
<%
		if (invoice.getRowCnt() > 0) {
			for (int i=0; i<invoice.getRowCnt(); i++) {
%>
			<tr>
				<td class="tdGrid Ct"><input type="checkbox" id="" name="chkForAction" class="chkEn inTblGrid" value="<%=invoice.getValue(i, "INVOICE_ID")%>"/></td>
				<td class="tdGrid Ct"><%=invoice.getValue(i, "INVOICE_ID")%></td>
				<td class="tdGrid Ct"><%=invoice.getValue(i, "INVOICE_NUMBER")%></td>
				<td class="tdGrid Ct"><%=invoice.getValue(i, "PARENT_INVOICE_ID")%></td>
				<td class="tdGrid Ct"><%=invoice.getValue(i, "INVOICE_DATE")%></td>
				<td class="tdGrid Rt"><%=CommonUtil.getNumberMask(invoice.getValue(i, "INVOICE_AMOUNT"), "#,##0.00")%></td>
				<td class="tdGrid Rt"><%=CommonUtil.getNumberMask(invoice.getValue(i, "GST_AMOUNT"), "#,##0.00")%></td>
				<td class="tdGrid Rt"><%=CommonUtil.toString(CommonUtil.toDouble(invoice.getValue(i, "INVOICE_AMOUNT")) - CommonUtil.toDouble(invoice.getValue(i, "GST_AMOUNT")), "#,##0.00")%></td>
				<td class="tdGrid Lt"><%=invoice.getValue(i, "STATUS_MEANING")%></td>
				<td class="tdGrid Lt"><%=invoice.getValue(i, "PAY_TO_ORG_NAME")%></td>
				<td class="tdGrid Ct"><%=invoice.getValue(i, "CON_PERIOD_START_DATE")%></td>
				<td class="tdGrid Ct"><%=invoice.getValue(i, "CON_PERIOD_END_DATE")%></td>
			</tr>
<%
			}
		} else {
%>
			<tr>
				<td class="tdGrid Ct" colspan="12"><mc:msg key="I001"/></td>
			</tr>
<%
		}
%>
		</tbody>
	</table>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>