/**************************************************************************************************
 * project
 * Description - Sys9808 - PERCI Source Generator
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sys.sys9808;

import org.springframework.beans.factory.annotation.Autowired;

import project.common.extend.BaseAction;
import zebra.data.DataSet;

public class Sys9808Action extends BaseAction {
	@Autowired
	private Sys9808Biz biz;

	public String getDefault() throws Exception {
		biz.getDefault(paramEntity);
		return "list";
	}

	public String getList() throws Exception {
		try {
			biz.getList(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}

	public String getDetail() throws Exception {
		biz.getDetail(paramEntity);
		return "detail";
	}

	public String getGeneratorInfo() throws Exception {
		biz.getGeneratorInfo(paramEntity);
		return "info";
	}

	public String exeGenerate() throws Exception {
		try {
			biz.exeGenerate(paramEntity);
			paramEntity.setAjaxResponseDataSet((DataSet)paramEntity.getObject("resultDataSet"));
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}
}