/**************************************************************************************************
 * project
 * Description - Sys9808 - PERCI Source Generator
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sys.sys9808;

import zebra.data.ParamEntity;

public interface Sys9808Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getDetail(ParamEntity paramEntity) throws Exception;
	public ParamEntity getGeneratorInfo(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeGenerate(ParamEntity paramEntity) throws Exception;
}