/**************************************************************************************************
 * project
 * Description - Sys9898 - Monitor Databse Session
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sys.sys9898;

import org.springframework.beans.factory.annotation.Autowired;

import project.common.extend.BaseAction;

public class Sys9898Action extends BaseAction {
	@Autowired
	private Sys9898Biz biz;

	public String getDefault() throws Exception {
		biz.getDefault(paramEntity);
		return "list";
	}

	public String doSearch() throws Exception {
		try {
			biz.doSearch(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}

	public String getSql() throws Exception {
		biz.getSql(paramEntity);
		return "sqlText";
	}

	public String getSqlText() throws Exception {
		try {
			biz.getSqlText(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}

	public String exeKillSessions() throws Exception {
		try {
			biz.exeKillSessions(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}
}