<%/************************************************************************************************
* Description - PreviewPayslipRemittanceFrame - ICRCTI
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet dsRequest = (DataSet)paramEntity.getRequestDataSet();
	DataSet payslipMaster = (DataSet)paramEntity.getObject("payslipMaster");
	String orgLogoImgPath = ConfigUtil.getProperty("path.image.orgLogo");
	String orgLogoName = orgLogoImgPath+"/"+payslipMaster.getValue("LOGO_NAME");
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconPerci.png">
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
.areaContainerFramePayslipPreview {margin:0px 0px 0px 0px;padding:0px 0px 0px 0px;}
.payslipPreviewSection {padding:4px 4px;border:1px solid #DDDDDD;}
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
var personId = "<%=dsRequest.getValue("personId")%>";
var paymentId = "<%=dsRequest.getValue("paymentId")%>";
var assignmentId = "<%=dsRequest.getValue("assignmentId")%>";
var paymentDate = "<%=payslipMaster.getValue("PAYMENT_DATE_FORMAT")%>";
var invoiceDate = "<%=payslipMaster.getValue("INVOICE_DATE_FORMAT")%>";
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body class="bodyFrame">
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divFrameWindowHolder">
<div id="divFixedPanelFrame">
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight"></div>
</div>
<div id="divSearchCriteriaArea"></div>
<div id="divInformArea"></div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelFrame">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerFramePayslipPreview">
	<div style="font-weight:bold;font-size:20px;text-align:center;padding:4px 8px 10px 8px;">Tax Invoice</div>
	<div style="font-weight:bold;font-size:16px;text-align:center;padding:4px 8px 4px 8px;"><%=payslipMaster.getValue("EMP_ORG_NAME")%></div>
	<div style="font-weight:bold;font-size:16px;text-align:center;padding:4px 8px 10px 8px;"><%=payslipMaster.getValue("EMP_ORG_ADDR")%></div>
	<div class="verGap2"></div>
	<div class="payslipPreviewSection">
		<table class="tblDefault withPadding">
			<colgroup>
				<col width="50%"/>
				<col width="20%"/>
				<col width="*"/>
			</colgroup>
			<tr>
				<th class="thDefault">To</th>
				<th class="thDefault"></th>
				<td class="tdDefault"></td>
			</tr>
			<tr>
				<th class="thDefault"><%=payslipMaster.getValue("RECIPIENT_ORG_NAME")%></th>
				<th class="thDefault Rt">GST Number</th>
				<td class="tdDefault"><%=payslipMaster.getValue("GST_NUMBER")%></td>
			</tr>
			<tr>
				<th class="tdDefault"><%=payslipMaster.getValue("RECIPIENT_ORG_ADDR_1")%></th>
				<th class="thDefault Rt">Date Of Invoice</th>
				<td class="tdDefault"><%=payslipMaster.getValue("INVOICE_DATE_FORMAT")%></td>
			</tr>
			<tr>
				<th class="tdDefault"><%=payslipMaster.getValue("RECIPIENT_ORG_ADDR_2")%></th>
				<th class="thDefault Rt">Invoice Number</th>
				<td class="tdDefault"><%=payslipMaster.getValue("PAYMENT_ID")%></td>
			</tr>
			<tr>
				<th class="thDefault"></th>
				<th class="thDefault Rt">Period Covered</th>
				<td class="tdDefault"><%=payslipMaster.getValue("PERIOD_START_FORMAT")%> - <%=payslipMaster.getValue("PERIOD_END_FORMAT")%></td>
			</tr>
		</table>
	</div>
	<div id="divEarning">
		<div class="verGap2"></div>
		<table id="tblEarning" class="tblGrid sort autosort">
			<colgroup>
				<col width="*"></col>
				<col width="14%"></col>
				<col width="14%"></col>
				<col width="14%"></col>
			</colgroup>
			<thead>
				<tr class="noStripe">
					<th class="thGrid">Description of taxable supplies</th>
					<th class="thGrid">Units</th>
					<th class="thGrid">Rate</th>
					<th class="thGrid">Amount</th>
				</tr>
			</thead>
			<tbody id="tbodyEarning">
				<tr class="noStripe">
					<td class="tdGrid Ct" colspan="4"><mc:msg key="I001"/></td>
				</tr>
			</tbody>
		</table>
	</div>
	<div id="divICRCTIValues">
		<div class="verGap2"></div>
		<table id="tblICRCTIValues" class="tblDefault withPadding">
			<colgroup>
				<col width="*"></col>
				<col width="14%"></col>
			</colgroup>
			<tr>
				<th class="thDefault Rt">Total</th>
				<td class="tdDefault Rt" id="tdSubTotal"></td>
			</tr>
			<tr>
				<th class="thDefault Rt">Plus 15% GST Due</th>
				<td class="tdDefault Rt" id="tdGST"></td>
			</tr>
			<tr>
				<th class="thDefault Rt">Total Including GST</th>
				<td class="tdDefault Rt" id="tdTotal"></td>
			</tr>
		</table>
	</div>
	<div id="divBankDetail">
		<div class="verGap2"></div>
		<table id="tblBankDetail" class="tblGrid sort autosort">
			<colgroup>
				<col width="*"></col>
				<col width="21%"></col>
				<col width="21%"></col>
				<col width="14%"></col>
			</colgroup>
			<thead>
				<tr class="noStripe">
					<th class="thGrid">Bank</th>
					<th class="thGrid">BSB</th>
					<th class="thGrid">Account Number</th>
					<th class="thGrid">Amount</th>
				</tr>
			</thead>
			<tbody id="tbodyBankDetail">
				<tr class="noStripe">
					<td class="tdGrid Ct" colspan="4"><mc:msg key="I001"/></td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>