<%/************************************************************************************************
* Description - PreviewPayslipRemittanceFrame - ICRCTI
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet dsRequest = (DataSet)paramEntity.getRequestDataSet();
	DataSet rctiMaster = (DataSet)paramEntity.getObject("rctiMaster");
	DataSet nrctiMaster = (DataSet)paramEntity.getObject("nrctiMaster");
	String orgLogoImgPath = ConfigUtil.getProperty("path.image.orgLogo");
	String orgLogoNameRcti = orgLogoImgPath+"/"+rctiMaster.getValue("LOGO_NAME");
	String orgLogoNameNRcti = orgLogoImgPath+"/"+nrctiMaster.getValue("LOGO_NAME");
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconPerci.png">
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
.areaContainerFramePayslipPreview {margin:0px 0px 0px 0px;padding:0px 0px 0px 0px;}
.payslipPreviewSection {padding:4px 4px;border:1px solid #DDDDDD;}
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
var personId = "<%=dsRequest.getValue("personId")%>";
var paymentId = "<%=dsRequest.getValue("paymentId")%>";
var assignmentId = "<%=dsRequest.getValue("assignmentId")%>";
var paymentDate = "<%=rctiMaster.getValue("PAYMENT_DATE_FORMAT")%>";
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body class="bodyFrame">
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divFrameWindowHolder">
<div id="divFixedPanelFrame">
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight"></div>
</div>
<div id="divSearchCriteriaArea"></div>
<div id="divInformArea"></div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelFrame" style="overflow:auto;">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerFramePayslipPreview">
	<div style="padding:4px 4px;border:1px solid #dddddd;">
		<div style="font-weight:bold;font-size:16px;text-align:center;padding:4px 8px 10px 8px;">Recipient Created Tax Invoice</div>
		<div class="payslipPreviewSection">
			<div style="float:left;width:49%;"><img id="imgOrgLogoRcti" src="<%=orgLogoNameRcti%>"/></div>
			<div style="float:right;width:50%">
				<table class="tblDefault withPadding">
					<colgroup>
						<col width="38%"/>
						<col width="*"/>
					</colgroup>
					<tr>
						<th class="thDefault Rt">Date</th>
						<td class="tdDefault"><%=rctiMaster.getValue("PAYMENT_CREATION_DATE_FORMAT")%></td>
					</tr>
					<tr>
						<th class="thDefault Rt">Invoice Number</th>
						<td class="tdDefault"><%=rctiMaster.getValue("PAYMENT_ID")%></td>
					</tr>
				</table>
			</div>
			<div class="breaker"></div>
		</div>
		<div class="verGap2"></div>
		<div class="payslipPreviewSection">
			<table class="tblDefault withPadding">
				<colgroup>
					<col width="10%"/>
					<col width="35%"/>
					<col width="10%"/>
					<col width="*"/>
				</colgroup>
				<tr>
					<th class="thDefault" colspan="2">From - Recipient</th>
					<th class="thDefault" colspan="2">To - Supplier</th>
				</tr>
				<tr>
					<th class="thDefault Rt">Name</th>
					<td class="tdDefault"><%=rctiMaster.getValue("RECIPIENT_ORG_NAME")%></td>
					<th class="thDefault Rt">Name</th>
					<td class="tdDefault"><%=rctiMaster.getValue("SUPPLIER_ORG_NAME")%></td>
				</tr>
				<tr>
					<th class="thDefault Rt">ABN</th>
					<td class="tdDefault"><%=rctiMaster.getValue("RECIPIENT_ORG_ABN")%></td>
					<th class="thDefault Rt">ABN</th>
					<td class="tdDefault"><%=rctiMaster.getValue("SUPPLIER_ORG_ABN")%></td>
				</tr>
				<tr>
					<th class="thDefault Rt"></th>
					<td class="tdDefault"></td>
					<th class="thDefault Rt">Consultant</th>
					<td class="tdDefault"><%=rctiMaster.getValue("PERSON_NAME_NUMBER")%></td>
				</tr>
				<tr>
					<th class="thDefault" colspan="2">Supplies Made by Supplier to Recipient</th>
					<th class="thDefault Rt">Period</th>
					<td class="tdDefault"><%=rctiMaster.getValue("PERIOD_START_FORMAT")%> - <%=rctiMaster.getValue("PERIOD_END_FORMAT")%></td>
				</tr>
			</table>
		</div>
		<div id="divEarningRcti">
			<div class="verGap2"></div>
			<table id="tblEarningRcti" class="tblGrid sort autosort">
				<colgroup>
					<col width="*"></col>
					<col width="14%"></col>
					<col width="14%"></col>
					<col width="14%"></col>
				</colgroup>
				<thead>
					<tr class="noStripe">
						<th class="thGrid">Description of taxable supplies</th>
						<th class="thGrid">Units</th>
						<th class="thGrid">Rate</th>
						<th class="thGrid">Amount</th>
					</tr>
				</thead>
				<tbody id="tbodyEarningRcti">
					<tr class="noStripe">
						<td class="tdGrid Ct" colspan="4"><mc:msg key="I001"/></td>
					</tr>
				</tbody>
			</table>
		</div>
		<div id="divValuesRcti">
			<div class="verGap2"></div>
			<table id="tblValuesRcti" class="tblDefault withPadding">
				<colgroup>
					<col width="*"></col>
					<col width="14%"></col>
				</colgroup>
				<tr>
					<th class="thDefault Rt">Sub-Total (Excludes GST)</th>
					<td class="tdDefault Rt" id="tdSubTotalRcti"></td>
				</tr>
				<tr>
					<th class="thDefault Rt">GST</th>
					<td class="tdDefault Rt" id="tdGSTRcti"></td>
				</tr>
				<tr>
					<th class="thDefault Rt">Total (Includes GST)</th>
					<td class="tdDefault Rt" id="tdTotalRcti"></td>
				</tr>
			</table>
		</div>
		<div class="verGap20"></div>
		The GST shown will form part of the total GST payable by the supplier on the business activity statement (BAS) for the relevant tax period.
		<div class="verGap20"></div>
		<div style="font-weight:bold;font-size:12px;border:0px;">Written Agreement</div>
		<div class="verGap6"></div>
		The recipient and the supplier declare that this agreement relates to the above supplies.
		<br/>
		The recipient will issue tax invoices in respect of these supplies.
		<br/>
		The supplier will not issue tax invoices in respect of these supplies.
		<br/>
		The supplier acknowledges that it is registered for GST and that it will notify the recipient if it ceases to be registered.
		<br/>
		<br/>
		* The recipient acknowledges that it is registered for GST and that it will notify the supplier if it ceases to be registered. Acceptance of this recipient created tax invoice (RCTI) constitues acceptance of the terms of this written agreement. Both parties to this supply agree that they are parties to an RCTI agreement as outlined in GSTS 2000/10. The supplier agrees to notify the recipient if the supplier does not wish to accept the proposed agreement.
		<br/>
		<br/>
		* This sentence will not apply if the supplier is not registered for GST.
	</div>
	<div class="verGap20"></div>
	<div style="padding:4px 4px;border:1px solid #dddddd;">
		<div style="font-weight:bold;font-size:16px;text-align:center;padding:4px 8px 10px 8px;">Remittance Advice</div>
		<div class="payslipPreviewSection">
			<div style="float:left;width:49%;"><img id="imgOrgLogoNRcti" src="<%=orgLogoNameNRcti%>"/></div>
			<div style="float:right;width:50%">
				<table class="tblDefault withPadding">
					<tr>
						<td class="tdDefault Rt"><%=nrctiMaster.getValue("BILLING_ORG_NAME")%></td>
					</tr>
					<tr>
						<td class="tdDefault Rt"><%=nrctiMaster.getValue("BILLING_ORG_ABN")%></td>
					</tr>
					<tr>
						<td class="tdDefault Rt"><%=nrctiMaster.getValue("BILLING_ORG_ADDR")%></td>
					</tr>
				</table>
			</div>
			<div class="breaker"></div>
		</div>
		<div class="verGap2"></div>
		<div class="payslipPreviewSection">
			<table class="tblDefault withPadding">
				<colgroup>
					<col width="55%"/>
					<col width="10%"/>
					<col width="*"/>
				</colgroup>
				<tr>
					<td class="tdDefault"><%=nrctiMaster.getValue("PERSON_NAME_NUMBER")%></td>
					<th class="thDefault Rt">Date</th>
					<td class="tdDefault"><%=nrctiMaster.getValue("PAYMENT_DATE_FORMAT")%></td>
				</tr>
				<tr>
					<td class="tdDefault"><%=nrctiMaster.getValue("PERSON_ADDR_1")%></td>
					<th class="thDefault Rt">Period</th>
					<td class="tdDefault"><%=nrctiMaster.getValue("PERIOD_START_FORMAT")%> - <%=nrctiMaster.getValue("PERIOD_END_FORMAT")%></td>
				</tr>
				<tr>
					<td class="tdDefault" colspan="3"><%=nrctiMaster.getValue("PERSON_ADDR_2")%></td>
				</tr>
			</table>
		</div>
		<div id="divBankDetailNRcti">
			<div class="verGap2"></div>
			<table id="tblBankDetailNRcti" class="tblGrid sort autosort">
				<colgroup>
					<col width="*"></col>
					<col width="21%"></col>
					<col width="21%"></col>
					<col width="14%"></col>
				</colgroup>
				<thead>
					<tr class="noStripe">
						<th class="thGrid">Bank</th>
						<th class="thGrid">BSB</th>
						<th class="thGrid">Account Number</th>
						<th class="thGrid">Amount</th>
					</tr>
				</thead>
				<tbody id="tbodyBankDetailNRcti">
					<tr class="noStripe">
						<td class="tdGrid Ct" colspan="4"><mc:msg key="I001"/></td>
					</tr>
				</tbody>
			</table>
		</div>
		<div id="divEarningNRcti">
			<div class="verGap2"></div>
			<table id="tblEarningNRcti" class="tblGrid sort autosort">
				<colgroup>
					<col width="*"></col>
					<col width="21%"></col>
					<col width="14%"></col>
				</colgroup>
				<thead>
					<tr class="noStripe">
						<th class="thGrid">Description</th>
						<th class="thGrid">Units</th>
						<th class="thGrid">Amount</th>
					</tr>
				</thead>
				<tbody id="tbodyEarningNRcti">
					<tr class="noStripe">
						<td class="tdGrid Ct" colspan="3"><mc:msg key="I001"/></td>
					</tr>
				</tbody>
			</table>
		</div>
		<div id="divValuesNRcti">
			<div class="verGap2"></div>
			<table id="tblValuesNRcti" class="tblDefault withPadding">
				<colgroup>
					<col width="*"></col>
					<col width="14%"></col>
				</colgroup>
				<tr>
					<th class="thDefault Rt">Sub-Total (Excludes GST)</th>
					<td class="tdDefault Rt" id="tdSubTotalNRcti"></td>
				</tr>
				<tr>
					<th class="thDefault Rt">GST</th>
					<td class="tdDefault Rt" id="tdGSTNRcti"></td>
				</tr>
				<tr>
					<th class="thDefault Rt">Super</th>
					<td class="tdDefault Rt" id="tdSuperNRcti"></td>
				</tr>
				<tr>
					<th class="thDefault Rt">Super Sal Sac</th>
					<td class="tdDefault Rt" id="tdSuperSalSacNRcti"></td>
				</tr>
				<tr>
					<th class="thDefault Rt">PAYG Taxation</th>
					<td class="tdDefault Rt" id="tdPAYGNRcti"></td>
				</tr>
				<tr>
					<th class="thDefault Rt">Other Taxation</th>
					<td class="tdDefault Rt" id="tdOtherTaxationNRcti"></td>
				</tr>
				<tr>
					<th class="thDefault Rt">Total (Includes GST)</th>
					<td class="tdDefault Rt" id="tdTotalNRcti"></td>
				</tr>
			</table>
		</div>
	</div>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>