/**************************************************************************************************
 * project
 * Description - SysMenu - Menu
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sys.sysAdmin.sysMenu;

import org.springframework.beans.factory.annotation.Autowired;

import project.common.extend.BaseAction;
import project.common.module.menu.MenuManager;
import zebra.util.CommonUtil;
import zebra.util.ConfigUtil;

public class SysMenuAction extends BaseAction {
	@Autowired
	private SysMenuBiz biz;

	public String getDefault() throws Exception {
		biz.getDefault(paramEntity);
		return "list";
	}

	public String getList() throws Exception {
		try {
			biz.getList(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}

	public String getEdit() throws Exception {
		biz.getEdit(paramEntity);
		if (CommonUtil.equalsIgnoreCase(ConfigUtil.getProperty("type.menuCreationType"), "Name")) {
			return "editN";
		} else {
			return "editC";
		}
	}

	public String getDetailData() throws Exception {
		try {
			biz.getDetailData(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}

	public String getUpdateSortOrder() throws Exception {
		biz.getUpdateSortOrder(paramEntity);
		return "updateSort";
	}

	public String doSave() throws Exception {
		try {
			biz.doSave(paramEntity);
			MenuManager.reload();
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}

	public String doDelete() throws Exception {
		try {
			biz.doDelete(paramEntity);
			MenuManager.reload();
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}

	public String doUpdateSortOrder() throws Exception {
		try {
			biz.doUpdateSortOrder(paramEntity);
			MenuManager.reload();
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", this.paramEntity);
		return "ajaxResponse";
	}

	public String doExport() throws Exception {
		biz.doExport(paramEntity);
		setRequestAttribute("paramEntity", paramEntity);
		return "export";
	}
}