/**************************************************************************************************
 * project
 * Description - SysPerciSourceGenerator - PERCI Source Generator
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sys.sysItSupport.sysPerciSourceGenerator;

import zebra.data.ParamEntity;

public interface SysPerciSourceGeneratorBiz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getDetail(ParamEntity paramEntity) throws Exception;
	public ParamEntity getGeneratorInfo(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeGenerate(ParamEntity paramEntity) throws Exception;
}