/**************************************************************************************************
 * project
 * Description - SysItSupportEtc - ETC
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sys.sysItSupport.sysItSupportEtc;

import zebra.data.ParamEntity;

public interface SysItSupportEtcBiz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getOrgInfo(ParamEntity paramEntity) throws Exception;
	public ParamEntity getBillingCodeInfo(ParamEntity paramEntity) throws Exception;
	public ParamEntity doSaveOrg(ParamEntity paramEntity) throws Exception;
	public ParamEntity doSaveBillingCodeCreationType(ParamEntity paramEntity) throws Exception;
	public ParamEntity doSaveAccntShift(ParamEntity paramEntity) throws Exception;
	public ParamEntity doUpdateEoExpenseStatus(ParamEntity paramEntity) throws Exception;
}