/**************************************************************************************************
 * project
 * Description - Qm10 - Select Dtabase
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.qm.qm10;

import org.springframework.beans.factory.annotation.Autowired;

import project.common.extend.BaseAction;

public class Qm10Action extends BaseAction {
	@Autowired
	private Qm10Biz biz;

	public String getDefault() throws Exception {
		biz.getDefault(paramEntity);
		return "list";
	}

	public String getList() throws Exception {
		try {
			biz.getList(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}
}