/**************************************************************************************************
 * project
 * Description - Qm10 - Select Dtabase
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.qm.qm10;

import zebra.data.ParamEntity;

public interface Qm10Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
}