#############################################################################################
# Messages
#    - project.app.qm
#############################################################################################
# Button
qm.button.saveToSession=Save to session
# List - Search
qm.search.name=Person Name
qm.search.personNumber=Person Number
qm.search.personType=Person Type
qm.search.email=Email
qm.search.empOrg=Emp. Organisation
# List - Data Grid
qm.grid.id=Id
qm.grid.number=Number
qm.grid.userName=User Name
qm.grid.userEmail=User Email
qm.grid.payslipEmail=Payslip Email
qm.grid.surname=Surname
qm.grid.firstName=First Name
qm.grid.memberSince=Member Since
qm.grid.dateOfBirth=DOB
qm.grid.personType=Person Type
qm.grid.empOrg=Employment Org
qm.grid.securityRole=Security Role
qm.grid.currBillingOrg=Current Billing Org
qm.grid.asgCount=ASG Count
qm.grid.paymentCount=Payment Count
# Header
qm.header.dataSource=Data Source
# Label
qm.label.dataSource=Data Source
# Message
login.message.descHeader=PERCI
login.message.confirmPassword=Password is not matched.
login.message.restart=Application will be restarting.