/**************************************************************************************************
 * project
 * Description - Qm40 - Find Assignment
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.qm.qm40;

import zebra.data.ParamEntity;

public interface Qm40Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeSave(ParamEntity paramEntity) throws Exception;
}