/**************************************************************************************************
 * project
 * Description - Per0202 - Person Profile
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.per.per0202;

import zebra.data.ParamEntity;

public interface Per0202Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getPersonDetailFrameContainer(ParamEntity paramEntity) throws Exception;
	public ParamEntity getPersonal(ParamEntity paramEntity) throws Exception;
	public ParamEntity getPersonDetail(ParamEntity paramEntity) throws Exception;
	public ParamEntity getPersonalComment(ParamEntity paramEntity) throws Exception;
	public ParamEntity getCommsHistory(ParamEntity paramEntity) throws Exception;
	public ParamEntity getContact(ParamEntity paramEntity) throws Exception;
	public ParamEntity getDocumentOutstanding(ParamEntity paramEntity) throws Exception;
	public ParamEntity getDocumentOutstandingList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getDocumentReceived(ParamEntity paramEntity) throws Exception;
	public ParamEntity getDocumentReceivedList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getAdditionalService(ParamEntity paramEntity) throws Exception;
	public ParamEntity getCommunication(ParamEntity paramEntity) throws Exception;
	public ParamEntity getNextActions(ParamEntity paramEntity) throws Exception;
}