/**************************************************************************************************
 * project
 * Description - Per0202 - Person Profile
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.per.per0202;

import zebra.data.ParamEntity;

public interface Per0202Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getPersonDetailFrameContainer(ParamEntity paramEntity) throws Exception;
	public ParamEntity getPersonal(ParamEntity paramEntity) throws Exception;
	public ParamEntity getPersonDetail(ParamEntity paramEntity) throws Exception;
	public ParamEntity getPersonalComment(ParamEntity paramEntity) throws Exception;
	public ParamEntity getCommsHistory(ParamEntity paramEntity) throws Exception;
	public ParamEntity getContact(ParamEntity paramEntity) throws Exception;
	public ParamEntity getDocumentOutstanding(ParamEntity paramEntity) throws Exception;
	public ParamEntity getDocumentOutstandingList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getDocumentReceived(ParamEntity paramEntity) throws Exception;
	public ParamEntity getDocumentReceivedList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getAdditionalService(ParamEntity paramEntity) throws Exception;
	public ParamEntity getAdditionalServiceList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getCommunication(ParamEntity paramEntity) throws Exception;
	public ParamEntity getCommunicationList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getNextActions(ParamEntity paramEntity) throws Exception;
	public ParamEntity getNextActionsList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getGeneral(ParamEntity paramEntity) throws Exception;
	public ParamEntity getGeneralInfo(ParamEntity paramEntity) throws Exception;
	public ParamEntity getWorkingRightsStatusList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getScheduledPayrollNotiList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getOpportunity(ParamEntity paramEntity) throws Exception;
	public ParamEntity getOpportunityList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getEditOpportunity(ParamEntity paramEntity) throws Exception;
	public ParamEntity getOpportunityDetail(ParamEntity paramEntity) throws Exception;
	public ParamEntity getOpportunityDocuments(ParamEntity paramEntity) throws Exception;
	public ParamEntity getAssignmentList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getAssignmentDataList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getAssignment(ParamEntity paramEntity) throws Exception;
	public ParamEntity getPrtDocumentList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getAssignmentRateList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getDeliverableRateList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getApproverEmail(ParamEntity paramEntity) throws Exception;
	public ParamEntity getNotiToPersonList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getPayslips(ParamEntity paramEntity) throws Exception;
	public ParamEntity getPayslipList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getSuperannuation(ParamEntity paramEntity) throws Exception;
}