/**************************************************************************************************
 * project
 * Description - Per0202 - Person Profile
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.per.per0202;

import org.springframework.beans.factory.annotation.Autowired;

import project.common.extend.BaseAction;
import project.conf.resource.ormapper.dto.oracle.HpPersonD;

public class Per0202Action extends BaseAction {
	@Autowired
	private Per0202Biz biz;

	public String getDefault() throws Exception {
		biz.getDefault(paramEntity);
		return "list";
	}

	public String getList() throws Exception {
		try {
			biz.getList(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}

	public String getPersonDetailFrameContainer() throws Exception {
		biz.getPersonDetailFrameContainer(paramEntity);

		if (paramEntity.isSuccess()) {
			HpPersonD hpPersonD = (HpPersonD)paramEntity.getObject("hpPersonD");

			session.setAttribute("PersonIdForAdminTool", hpPersonD.getPersonId());
			session.setAttribute("PersonNumberForAdminTool", hpPersonD.getPersonNumber());
			session.setAttribute("PersonFullNameForAdminTool", hpPersonD.getFullName());
			session.setAttribute("HpPersonDForAdminTool", hpPersonD);

			session.setAttribute("PersonIdQuickSearch", hpPersonD.getPersonId());
			session.setAttribute("PersonNumberQuickSearch", hpPersonD.getPersonNumber());
			session.setAttribute("PersonFullNameQuickSearch", hpPersonD.getFullName());
			session.setAttribute("HpPersonDQuickSearch", hpPersonD);
		}
		return "personDetailFrameContainer";
	}

	public String getPersonal() throws Exception {
		biz.getPersonal(paramEntity);
		return "personal";
	}

	public String getPersonDetail() throws Exception {
		try {
			biz.getPersonDetail(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}

	public String getPersonalComment() throws Exception {
		try {
			biz.getPersonalComment(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}

	public String getCommsHistory() throws Exception {
		try {
			biz.getCommsHistory(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}

	public String getContact() throws Exception {
		biz.getContact(paramEntity);
		return "contact";
	}

	public String getDocumentOutstanding() throws Exception {
		biz.getDocumentOutstanding(paramEntity);
		return "documentOutstanding";
	}

	public String getDocumentReceived() throws Exception {
		biz.getDocumentReceived(paramEntity);
		return "documentReceived";
	}

	public String getAdditionalService() throws Exception {
		biz.getAdditionalService(paramEntity);
		return "additionalService";
	}

	public String getCommunication() throws Exception {
		biz.getCommunication(paramEntity);
		return "communication";
	}

	public String getNextActions() throws Exception {
		biz.getNextActions(paramEntity);
		return "nextActions";
	}

/*
	public String getDetail() throws Exception {
		biz.getDetail(paramEntity);
		return "detail";
	}

	public String getInsert() throws Exception {
		biz.getInsert(paramEntity);
		return "insert";
	}

	public String getUpdate() throws Exception {
		biz.getUpdate(paramEntity);
		return "update";
	}

	public String exeInsert() throws Exception {
		try {
			biz.exeInsert(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}

	public String exeUpdate() throws Exception {
		try {
			biz.exeUpdate(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}

	public String exeDelete() throws Exception {
		try {
			biz.exeDelete(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}

	public String exeExport() throws Exception {
		biz.exeExport(paramEntity);
		setRequestAttribute("paramEntity", paramEntity);
		return "export";
	}
*/
}