<%/************************************************************************************************
* Description - Org0202 - Organisation Profile
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet dsRequest = (DataSet)paramEntity.getRequestDataSet();
	String organisationId = dsRequest.getValue("organisationId");
	HpOrganisationD organisation = (HpOrganisationD)paramEntity.getObject("HpOrganisationD");
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconPerci.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
/* .divTabArea {padding:0px 8px;} */
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
var organisationId = "<%=organisationId%>";
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divHeaderHolder" class="ui-layout-north"><%@ include file="/project/common/include/header.jsp"%></div>
<div id="divBodyHolder" class="ui-layout-center">
<div id="divBodyLeft" class="ui-layout-west"><%@ include file="/project/common/include/bodyLeft.jsp"%></div>
<div id="divBodyCenter" class="ui-layout-center">
<div id="divFixedPanel">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabAreaOrganisationDetail" class="divTabArea areaContainer">
	<ui:tab id="tabCategoryOrganisationDetail">
		<ui:tabList caption="Organisation" isActive="true" iconClass="fa-building" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Contact" iconClass="fa-address-book" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Employee" iconClass="fa-users" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Document" iconClass="fa-folder" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Communication" iconClass="fa-comments" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Next Action" iconClass="fa-tasks" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="ECMS" iconClass="fa-street-view" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Templated Document" iconClass="fa-folder-o" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Portal" iconClass="fa-cog" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Workcover" iconClass="fa-user-md" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Payroll Tax" iconClass="fa-university" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Contract" iconClass="fa-briefcase" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Rate Card" iconClass="fa-id-card" iconPosition="left" useAutoScript="false"/>
	</ui:tab>
</div>
<div id="divTabAreaEcms" class="divTabArea areaContainer" style="display:none">
	<ui:tab id="tabCategoryEcms">
		<ui:tabList caption="Assignments" iconClass="fa-id-card" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Services" iconClass="fa-calculator" iconPosition="left" useAutoScript="false"/>
	</ui:tab>
</div>
<div id="divTabAreaWorkcover" class="divTabArea areaContainer" style="display:none">
	<ui:tab id="tabCategoryWorkcover">
		<ui:tabList caption="Australian Capital Territory" useAutoScript="false"/>
		<ui:tabList caption="New South Wales" useAutoScript="false"/>
		<ui:tabList caption="Northern Territory" useAutoScript="false"/>
		<ui:tabList caption="Queensland" useAutoScript="false"/>
		<ui:tabList caption="South Australia" useAutoScript="false"/>
		<ui:tabList caption="Tasmania" useAutoScript="false"/>
		<ui:tabList caption="Victoria" useAutoScript="false"/>
		<ui:tabList caption="Western Australia" useAutoScript="false"/>
	</ui:tab>
</div>
<div id="divTabAreaPayrollTax" class="divTabArea areaContainer" style="display:none">
	<ui:tab id="tabCategoryPayrollTax">
		<ui:tabList caption="Australian Capital Territory" useAutoScript="false"/>
		<ui:tabList caption="New South Wales" useAutoScript="false"/>
		<ui:tabList caption="Northern Territory" useAutoScript="false"/>
		<ui:tabList caption="Queensland" useAutoScript="false"/>
		<ui:tabList caption="South Australia" useAutoScript="false"/>
		<ui:tabList caption="Tasmania" useAutoScript="false"/>
		<ui:tabList caption="Victoria" useAutoScript="false"/>
		<ui:tabList caption="Western Australia" useAutoScript="false"/>
	</ui:tab>
</div>
<div id="divTabAreaRateCard" class="divTabArea areaContainer" style="display:none">
	<ui:tab id="tabCategoryRateCard">
		<ui:tabList caption="Assignment Rate" iconClass="fa-line-chart" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Assignment Deduction" iconClass="fa-area-chart" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Assignment Invoice" iconClass="fa-bar-chart" iconPosition="left" useAutoScript="false"/>
	</ui:tab>
</div>
<div id="divButtonArea">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight"></div>
</div>
<div id="divSearchCriteriaArea"></div>
<div id="divInformArea"></div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanel" style="overflow:hidden;">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea">
	<div id="divFrameContainer" class="frameContainer">
		<div id="divFrame" style="">
			<iframe id="ifFrame" class="iframeInFrameContainer"></iframe>
		</div>
	</div>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<div id="divBodyRight" class="ui-layout-east"><%@ include file="/project/common/include/bodyRight.jsp"%></div>
</div>
<div id="divFooterHolder" class="ui-layout-south"><%@ include file="/project/common/include/footer.jsp"%></div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>