<%/************************************************************************************************
* Description - Per0202 - Person Profile
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet dsRequest = (DataSet)paramEntity.getRequestDataSet();
	HpOrganisationD hpOrganisationD = (HpOrganisationD)paramEntity.getObject("hpOrganisationD");
	String organisationId = dsRequest.getValue("organisationId");
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconPerci.png">
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
#divOrganisationHeader {padding:8px;margin-bottom:0px;font-weight:bold;}
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
var organisationId = "<%=organisationId%>";
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body class="bodyFrame">
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divFrameWindowHolder">
<div id="divFixedPanelFrame">
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerFrame">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnNew" caption="button.com.new" iconClass="fa-plus-square"/>
			<ui:button id="btnSave" caption="button.com.save" iconClass="fa-save"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea">
</div>
<div id="divInformArea" class="areaContainerFrame">
	<div id="divOrganisationHeader" class="alert alert-info"><%=hpOrganisationD.getOrganisationName()%> (<%=organisationId%>)</div>
</div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelFrame">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerFrame">
	<div id="divFrameDataAreaWrapper" style="overflow:auto">
		<div id="divLeft" class="accordion" style="width:49%;float:left">
			<div class="accordionGroup">
				<h3>Organisation Details</h3>
				<div id="divOrganisationDetails" class="accordionContents">
					<table id="tblOrganisationDetails" class="tblEdit">
						<colgroup>
							<col width="15%"/>
							<col width="35%"/>
							<col width="15%"/>
							<col width="35%"/>
						</colgroup>
						<tbody>
							<tr>
								<th class="thEdit rt">Is Dormant?</th>
								<td class="tdEdit"><ui:ccradio name="isDormant" codeType="SIMPLE_YN"  isCustomised="true"/></td>
								<th class="thEdit rt mandatory">Organisation Id</th>
								<td class="tdEdit"><ui:text name="organisationId" status="display"/></td>
							</tr>
							<tr>
								<th class="thEdit rt mandatory">Organisation Name</th>
								<td class="tdEdit" colspan="3"><ui:text name="organisationName" options="mandatory" checkName="Organisation Name"/></td>
							</tr>
							<tr>
								<th class="thEdit rt">First Contact</th>
								<td class="tdEdit"><ui:text name="firstContactDate" className="Ct hor" style="width:90px" option="date"/><ui:icon id="icnFirstContactDate" className="fa-calendar hor"/></td>
								<th class="thEdit rt"></th>
								<td class="tdEdit"></td>
							</tr>
							<tr>
								<th class="thEdit rt">Address</th>
								<td class="tdEdit" colspan="3"><ui:text name="addressLine" status="display"/></td>
							</tr>
							<tr>
								<th class="thEdit rt">Jurisdiction</th>
								<td class="tdEdit"><ui:text name="country" status="display"/></td>
								<th class="thEdit rt">Web Address</th>
								<td class="tdEdit"><ui:text name="webAddress"/></td>
							</tr>
							<tr>
								<th class="thEdit rt">Role</th>
								<td class="tdEdit"><ui:ccselect name="role" codeType="ORGANISATION_ROLE" isMultiple="true" attribute="data-width:100%" checkName="Organisation Role"/></td>
								<th class="thEdit rt mandatory">Relationship</th>
								<td class="tdEdit"><ui:ccselect name="relationship" codeType="ORGANISATION_RELATIONSHIP" isMultiple="true" attribute="data-width:100%" options="mandatory" checkName="Relationship"/></td>
							</tr>
							<tr>
								<th class="thEdit rt">Overview</th>
								<td class="tdEdit" colspan="3"><ui:txa id="organisationOverview" name="organisationOverview" style="height:70px;"/></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div class="accordionGroup">
				<h3>Customer Details</h3>
				<div id="divCustomerDetails" class="accordionContents">
					<table id="tblCustomerDetails" class="tblEdit">
						<colgroup>
							<col width="15%"/>
							<col width="35%"/>
							<col width="15%"/>
							<col width="35%"/>
						</colgroup>
						<tbody>
							<tr>
								<th class="thEdit rt">Product</th>
								<td class="tdEdit"><ui:ccselect name="product" codeType="ORGANISATION_PRODUCT" isMultiple="true" attribute="data-width:100%" checkName="Product"/></td>
								<th class="thEdit rt mandatory">Organisation Type</th>
								<td class="tdEdit"><ui:ccselect name="product" codeType="ORGANISATION_TYPES" attribute="data-width:100%" checkName="Organisation Type"/></td>
							</tr>
							<tr>
								<th class="thEdit rt">Customer Type</th>
								<td class="tdEdit"><ui:ccselect name="customerType" codeType="ORGANISATION_CUSTOMER_TYPE" attribute="data-width:100%"/></td>
								<th class="thEdit rt">Customer Category</th>
								<td class="tdEdit"><ui:ccselect name="customerCategory" codeType="CUSTOMER_CATEGORY" attribute="data-width:100%"/></td>
							</tr>
							<tr>
								<th class="thEdit rt">Swim Lane</th>
								<td class="tdEdit"><ui:ccselect name="swimLane" codeType="SWIM_LANE" attribute="data-width:100%"/></td>
								<th class="thEdit rt"></th>
								<td class="tdEdit"></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div id="divRight" class="accordion" style="width:50%;float:right">
			<div class="accordionGroup" style="width:49%;float:left;">
				<h3>Company Details</h3>
				<div id="divCompanyDetails" class="accordionContents">
					CompanyDetails
				</div>
			</div>
			<div class="accordionGroup" style="width:50%;float:right;">
				<h3>Entity Relationship / Internal Details</h3>
				<div id="divRelationshipInternalDetails" class="accordionContents">
					RelationshipInternalDetails
				</div>
			</div>
			<div class="breaker"></div>
			<div class="accordionGroup">
				<h3>Communication History - Latest 50</h3>
				<div id="divCommsHistory" class="accordionContents">
					<div class="divButtonArea">
						<div class="divButtonAreaLeft"></div>
						<div class="divButtonAreaRight">
							<ui:buttonGroup>
								<ui:button id="btnAddComms" caption="button.com.add" iconClass="fa-plus-square"/>
								<ui:button id="btnDownloadComms" caption="Download" iconClass="fa-download"/>
							</ui:buttonGroup>
						</div>
					</div>
					<div class="verGap4"></div>
					<div id="commsHistory" style="padding:6px;height:325px;border:1px solid #cccccc;border-radius:3px;overflow:auto;"></div>
				</div>
			</div>
			<div class="accordionGroup">
				<h3>Additional Information</h3>
				<div id="divAdditionalInfo" class="accordionContents">
					Additional Information
				</div>
			</div>
		</div>
	</div>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>