/**************************************************************************************************
 * project
 * Description - Qm30 - Find Organisation
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.qm.qm30;

import zebra.data.ParamEntity;

public interface Qm30Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeSave(ParamEntity paramEntity) throws Exception;
}