/**************************************************************************************************
 * project
 * Description - Sys9806 - Site Running Test
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sys.sys9899;

import zebra.data.ParamEntity;

public interface Sys9899Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity doSearch(ParamEntity paramEntity) throws Exception;
}