/**************************************************************************************************
 * project
 * Description - Sys9899 - Site Running Test
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sys.sys9899;

import org.springframework.beans.factory.annotation.Autowired;

import project.common.extend.BaseAction;

public class Sys9899Action extends BaseAction {
	@Autowired
	private Sys9899Biz biz;

	public String getDefault() throws Exception {
		biz.getDefault(paramEntity);
		return "list";
	}

	public String doSearch() throws Exception {
		try {
			biz.doSearch(paramEntity);
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}
}