/**************************************************************************************************
 * project
 * Description - Sys9802 - Assignment
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sys.sys9802;

import zebra.data.ParamEntity;

public interface Sys9802Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getDetail(ParamEntity paramEntity) throws Exception;
	public ParamEntity getUnlockPrt(ParamEntity paramEntity) throws Exception;
	public ParamEntity getUpdateWorkingState(ParamEntity paramEntity) throws Exception;
	public ParamEntity getUpdateEndUser(ParamEntity paramEntity) throws Exception;
	public ParamEntity doUnlockPrt(ParamEntity paramEntity) throws Exception;
	public ParamEntity doUpdateWorkingState(ParamEntity paramEntity) throws Exception;
	public ParamEntity doUpdateEndUser(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeExport(ParamEntity paramEntity) throws Exception;
}