<%/************************************************************************************************
* Description - SysUser - User
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet requestDataSet = (DataSet)paramEntity.getRequestDataSet();
	DataSet authGroupDataSet = (DataSet)paramEntity.getObject("authGroupDataSet");
	String dateFormat = ConfigUtil.getProperty("format.date.java");
	String maxRowPerPage[] = (String[])paramEntity.getObject("maxRowPerPage");
	String pageNumPerPage[] = (String[])paramEntity.getObject("pageNumPerPage");
	String photoPath = (String)paramEntity.getObject("photoPath");
	String defaultAuthGroup = (String)paramEntity.getObject("defaultAuthGroup");
	String defaultUserStatus = CommonCodeManager.getCodeByConstants("USER_STATUS_NU");

	pageContext.setAttribute("maxRowPerPage", maxRowPerPage);
	pageContext.setAttribute("pageNumPerPage", pageNumPerPage);
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconPerci.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
var defaultAuthGroup = "<%=defaultAuthGroup%>";
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divPopupWindowHolder">
<div id="divFixedPanelPopup">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerPopup">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnSave" caption="button.com.save"/>
			<ui:button id="btnClose" caption="button.com.close"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea"></div>
<div id="divInformArea"></div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelPopup">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerPopup">
	<div class="panel panel-default" style="width:120px;height:110px;">
		<div class="panel-body">
			<table class="tblDefault">
				<tr>
					<td class="tdDefaultCt">
						<img id="imgUserPhoto" src="<%=photoPath%>" class="imgDis" style="width:90px;height:90px;"/>
					</td>
				</tr>
			</table>
		</div>
	</div>
	<table class="tblEdit">
		<colgroup>
			<col width="18%"/>
			<col width="32%"/>
			<col width="18%"/>
			<col width="32%"/>
		</colgroup>
		<tr>
			<th class="thEdit rt">Change Photo</th>
			<td class="tdEdit" colspan="3"><ui:file name="photoPath" style="width:540px;" checkName="Change Photo"/></td>
		</tr>
		<tr>
			<th class="thEdit rt">User Id</th>
			<td class="tdEdit"><ui:text name="userId" status="display"/></td>
			<th class="thEdit rt mandatory">User Name</th>
			<td class="tdEdit"><ui:text name="userName" checkName="User Name" options="mandatory"/></td>
		</tr>
		<tr>
			<th class="thEdit rt mandatory">Login Id</th>
			<td class="tdEdit"><ui:text name="loginId" checkName="Login Id" options="mandatory"/></td>
			<th class="thEdit rt mandatory">Login Password</th>
			<td class="tdEdit"><ui:password name="password" checkName="Login Password" options="mandatory"/></td>
		</tr>
		<tr>
			<th class="thEdit rt mandatory">Startup URL</th>
			<td class="tdEdit"><ui:text name="defaultStartUrl" value="/index/dashboard.do" checkName="Startup URL" options="mandatory"/></td>
			<th class="thEdit rt mandatory">Authority Group</th>
			<td class="tdEdit"><ui:select name="authGroup" checkName="Authority Group" options="mandatory"> </ui:select>
			</td>
		</tr>
		<tr>
			<th class="thEdit rt mandatory">Language</th>
			<td class="tdEdit"><ui:ccselect name="language" codeType="LANGUAGE_TYPE" options="mandatory"/></td>
			<th class="thEdit rt mandatory">Theme Type</th>
			<td class="tdEdit"><ui:ccselect name="themeType" codeType="USER_THEME_TYPE" options="mandatory"/></td>
		</tr>
		<tr>
			<th class="thEdit rt mandatory">User Type</th>
			<td class="tdEdit"><ui:ccselect name="userType" codeType="USER_TYPE" options="mandatory"/></td>
			<th class="thEdit rt mandatory">Email</th>
			<td class="tdEdit"><ui:text name="email" checkName="Email" options="mandatory" option="email"/></td>
		</tr>
		<tr>
			<th class="thEdit rt mandatory">Data Rows Per Page</th>
			<td class="tdEdit">
				<ui:select name="maxRowsPerPage" checkName="Data Rows Per Page" options="mandatory">
					<c:forEach var="idx" items="${maxRowPerPage}">
						<option value="${idx}">${idx}</option>
					</c:forEach>
				</ui:select>
			</td>
			<th class="thEdit rt mandatory">Page Count Per Page</th>
			<td class="tdEdit">
				<ui:select name="pageNumsPerPage" checkName="Page Count Per Page" options="mandatory">
					<c:forEach var="idx" items="${pageNumPerPage}">
						<option value="${idx}">${idx}</option>
					</c:forEach>
				</ui:select>
			</td>
		</tr>
		<tr>
			<th class="thEdit rt mandatory">User Status</th>
			<td class="tdEdit"><ui:ccselect name="userStatus" codeType="USER_STATUS" selectedValue="<%=defaultUserStatus%>" options="mandatory"/></td>
			<th class="thEdit rt mandatory">Is Active</th>
			<td class="tdEdit"><ui:ccselect name="isActive" codeType="IS_ACTIVE" options="mandatory"/></td>
		</tr>
		<tr>
			<th class="thEdit rt">Authentication Key</th>
			<td class="tdEdit" colspan="3">
				<ui:text name="authenticationSecretKey" value="" checkName="Authentication Key" className="hor" style="width:45%;"/>
				<ui:button id="btnGetAuthenticationSecretKey" caption="Generate Key" iconClass="fa-key"/>
			</td>
		</tr>
		<tr>
			<th class="thEdit rt">Created By</th>
			<td class="tdEdit"><ui:text name="insertUser" status="display"/></td>
			<th class="thEdit rt">Created Date</th>
			<td class="tdEdit"><ui:text name="insertDate" status="display"/></td>
		</tr>
		<tr>
			<th class="thEdit rt">Updated By</th>
			<td class="tdEdit"><ui:text name="updateUser" status="display"/></td>
			<th class="thEdit rt">Updated Date</th>
			<td class="tdEdit"><ui:text name="updateDate" status="display"/></td>
		</tr>
	</table>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>