/**************************************************************************************************
 * project
 * Description - Org0202 - Organisation Profile
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.org.org0202;

import zebra.data.ParamEntity;

public interface Org0202Biz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity getOrganisationDetailFrameContainer(ParamEntity paramEntity) throws Exception;
	public ParamEntity getOrganisation(ParamEntity paramEntity) throws Exception;
	public ParamEntity getOrganisationDetail(ParamEntity paramEntity) throws Exception;
	public ParamEntity getCommunicationHistory(ParamEntity paramEntity) throws Exception;
}