<%/************************************************************************************************
* Description - Per0202 - Person Profile
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet dsRequest = (DataSet)paramEntity.getRequestDataSet();
	String personId = dsRequest.getValue("personId");
	HpPersonD person = (HpPersonD)paramEntity.getObject("hpPersonD");
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconPerci.png">
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
#divPersonHeader {padding:8px;margin-bottom:0px;font-weight:bold;}
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
var personId = "<%=personId%>";
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body class="bodyFrame">
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divFrameWindowHolder">
<div id="divFixedPanelFrame">
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerFrame">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnSave" caption="button.com.save" iconClass="fa-save"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea">
</div>
<div id="divInformArea" class="areaContainerFrame">
	<div id="divPersonHeader" class="alert alert-info"><%=person.getFullName()%> (<%=person.getPersonNumber()%>) <%=person.getPersonType()%></div>
</div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelFrame">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerFrame">
	<div id="divFrameDataAreaWrapper" style="overflow:auto">
		<div id="divLeft" class="accordion" style="width:50%;float:left">
			<div class="accordionGroup">
				<h3 id="hHomeAddress">Postal Address</h3>
				<div id="divHomeAddress" class="accordionContents">
					<table id="tblHomeAddress" class="tblEdit">
						<colgroup>
							<col width="14%"/>
							<col width="36%"/>
							<col width="14%"/>
							<col width="*"/>
						</colgroup>
						<tbody>
							<tr>
								<th class="thEdit rt">Address Search</th>
								<td class="tdEdit" colspan="3">
									<ui:text name="homeAddressSearch" className="hor" style="width:83%" placeHolder="Enter a location"/>
									<ui:check name="editHomeAddress" labelClassName="withElem" value="Y" text="Edit Address"/>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div id="divRight" class="accordion" style="width:49%;float:right">
			<div class="accordionGroup">
				<h3 id="hEmail">Email</h3>
				<div id="divEmail" class="accordionContents">
					<table id="tblEmail" class="tblEdit">
						<colgroup>
							<col width="15%"/>
							<col width="*"/>
						</colgroup>
						<tbody>
							<tr>
								<th class="thEdit rt">Bulk Email</th>
								<td class="tdEdit"><ui:check name="excludeFromBulkEmail" value="Y" text="Exclude From Bulk Email"/></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>