<%/************************************************************************************************
* Description - Per0202 - Person Profile
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet dsRequest = (DataSet)paramEntity.getRequestDataSet();
	String personId = dsRequest.getValue("personId");
	String captionEcmsEbo = "";
	HpPersonD person = (HpPersonD)paramEntity.getObject("hpPersonD");
	String personType = person.getPersonType();
	String personTypeForPortalTab[] = {"ECMS IPro","ECMS IC","ECMS Sponsored IPro","ECMS Prospect", "BO Employee", "EST ECMS Sponsored IPro","NZ IC", "NZ IPro",
			"NZ Prospect", "ECMS Elite Premium IC","ECMS EES IPro","ECMS EES IC", "ECMS ESSG Contractor", "ECMS ESSG Pte Ltd Contractor", "ECMS ESSG SPass Contractor",
			"ECMS ESUK IPro", "ECMS ESUK IC", "ECMS ESMY Contractor", "ECMS EES IPro", "ECMS EES IC", "ECMS ESHK Ltd Co Contractor", "UoM Sole Trader", "UoM IC"};
	boolean isEcmsEboTabAvailable = false, isPortalTabAvailable = false;

	if (CommonUtil.contains(personType, "ECMS", "NZ", "UoM")) {
		isEcmsEboTabAvailable = true;
		captionEcmsEbo = "ECMS";
	} else if (CommonUtil.contains(personType, "EBO", "EES")) {
		isEcmsEboTabAvailable = true;
		captionEcmsEbo = "EBO";
	}

	if (CommonUtil.isIn(personType, personTypeForPortalTab)) {
		isPortalTabAvailable = true;
	}
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconPerci.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
/* .divTabArea {padding:0px 8px;} */
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
var personId = "<%=personId%>";
var assignmentId = "";
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divHeaderHolder" class="ui-layout-north"><%@ include file="/project/common/include/header.jsp"%></div>
<div id="divBodyHolder" class="ui-layout-center">
<div id="divBodyLeft" class="ui-layout-west"><%@ include file="/project/common/include/bodyLeft.jsp"%></div>
<div id="divBodyCenter" class="ui-layout-center">
<div id="divFixedPanel">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabAreaPersonDetail" class="divTabArea areaContainer">
	<ui:tab id="tabCategoryPersonDetail">
		<ui:tabList caption="Personal" isActive="true" iconClass="fa-user" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Contact" iconClass="fa-address-book" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Document" iconClass="fa-folder" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Additional Service" iconClass="fa-archive" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Communication" iconClass="fa-comments" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Next Actions" iconClass="fa-tasks" iconPosition="left" useAutoScript="false"/>
<%
	if (isEcmsEboTabAvailable) {
%>
		<ui:tabList caption="<%=captionEcmsEbo%>" iconClass="fa-street-view" iconPosition="left" useAutoScript="false"/>
<%
	}

	if (isPortalTabAvailable) {
%>
		<ui:tabList caption="Portal" iconClass="fa-users" iconPosition="left" useAutoScript="false"/>
<%
	}
%>
		<ui:tabList caption="Summary" iconClass="fa-id-card" iconPosition="left" useAutoScript="false"/>
	</ui:tab>
</div>
<div id="divTabAreaDocument" class="divTabArea areaContainer" style="display:none">
	<ui:tab id="tabCategoryDocument">
		<ui:tabList caption="Outstanding" iconClass="fa-file" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Received" iconClass="fa-file-text" iconPosition="left" useAutoScript="false"/>
	</ui:tab>
</div>
<div id="divTabAreaEcmsEbo" class="divTabArea areaContainer" style="display:none">
	<ui:tab id="tabCategoryEcmsEbo">
		<ui:tabList caption="General" iconClass="fa-user" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Opportunities" iconClass="fa-folder-open" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Assignments" iconClass="fa-id-card" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Payslips" iconClass="fa-money" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Superannuation" iconClass="fa-calculator" iconPosition="left" useAutoScript="false"/>
	</ui:tab>
</div>
<div id="divTabAreaPortal" class="divTabArea areaContainer" style="display:none">
	<ui:tab id="tabCategoryPortal">
		<ui:tabList caption="Account" iconClass="fa-users" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Task Flow" iconClass="fa-sitemap" iconPosition="left" useAutoScript="false"/>
	</ui:tab>
</div>
<div id="divTabAreaAssignments" class="divTabArea areaContainer" style="display:none">
	<ui:tab id="tabCategoryAssignments">
		<ui:tabList caption="Assignment List" iconClass="fa-bars" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Assignment" iconClass="fa-id-card-o" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Rate Calculator" iconClass="fa-calculator" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Deduction" iconClass="fa-minus-square" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Invoice" iconClass="fa-desktop" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Tax" iconClass="fa-usd" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Banking" iconClass="fa-university" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Leave" iconClass="fa-plane" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="Templated Documents" iconClass="fa-clone" iconPosition="left" useAutoScript="false"/>
		<ui:tabList caption="PERCI NAR" iconClass="fa-list-alt" iconPosition="left" useAutoScript="false"/>
	</ui:tab>
</div>
<div id="divButtonArea">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight"></div>
</div>
<div id="divAdminToolArea"><%@ include file="/project/common/include/bodyAdminToolArea.jsp"%></div>
<div id="divSearchCriteriaArea"></div>
<div id="divInformArea"></div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanel" style="overflow:hidden;">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea">
	<div id="divFrameContainer" class="frameContainer">
		<div id="divFrame" style="">
			<iframe id="ifFrame" class="iframeInFrameContainer"></iframe>
		</div>
	</div>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<div id="divBodyRight" class="ui-layout-east"><%@ include file="/project/common/include/bodyRight.jsp"%></div>
</div>
<div id="divFooterHolder" class="ui-layout-south"><%@ include file="/project/common/include/footer.jsp"%></div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>