<%/************************************************************************************************
* Description - Per0202 - Person Profile
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	HpPersonD hpPersonD = (HpPersonD)session.getAttribute("HpPersonDQuickSearch");
	String personNumber = "", personName = "";
	if (hpPersonD != null) {
		personNumber = hpPersonD.getPersonNumber();
		personName = hpPersonD.getFullName();
	}
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconPerci.png">
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divFrameWindowHolder">
<div id="divFixedPanelFrame">
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerFrame">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnSave" caption="button.com.save" iconClass="fa-save"/>
			<ui:button id="btnClose" caption="button.com.close" iconClass="fa-times"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea" class="areaContainerFrame">
	<div class="panel panel-default">
		<div class="panel-body">
			<table class="tblDefault withPadding">
				<colgroup>
					<col width="10%"/>
					<col width="23%"/>
					<col width="10%"/>
					<col width="23%"/>
					<col width="10%"/>
					<col width="24%"/>
				</colgroup>
				<tr>
					<th class="thDefault rt"><mc:msg key="per0202.search.personNumber"/></th>
					<td class="tdDefault"><ui:text name="personNumber" value="<%=personNumber%>" style="width:280px"/></td>
					<th class="thDefault rt"><mc:msg key="per0202.search.name"/></th>
					<td class="tdDefault"><ui:text name="name" value="<%=personName%>" style="width:280px"/></td>
					<th class="thDefault rt"><mc:msg key="per0202.search.email"/></th>
					<td class="tdDefault"><ui:text name="email" style="width:280px"/></td>
				</tr>
				<tr>
					<th class="thDefault rt"><mc:msg key="per0202.search.empOrg"/></th>
					<td class="tdDefault">
						<ui:hidden name="empOrgId"/>
						<ui:text name="empOrgName" className="hor" style="width:280px"/>
<%-- 						<ui:icon id="icnEmpOrgSearch" className="fa-search hor"/> --%>
					</td>
					<th class="thDefault rt"><mc:msg key="per0202.search.personType"/></th>
					<td class="tdDefault"><ui:ccselect name="personType" codeType="PERSON_TYPES" isMultiple="true" attribute="data-size:20;data-width:280px"/></td>
					<th class="thDefault rt"><mc:msg key="per0202.search.mobile"/></th>
					<td class="tdDefault"><ui:text name="mobile" style="width:280px"/></td>
				</tr>
			</table>
		</div>
	</div>
</div>
<div id="divInformArea"></div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelFrame">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerFrame">
	<table id="tblGrid" class="tblGrid sort autosort">
		<colgroup>
			<col width="2%"/>
			<col width="5%"/>
			<col width="13%"/>
			<col width="13%"/>
			<col width="*"/>
			<col width="21%"/>
			<col width="16%"/>
			<col width="8%"/>
			<col width="4%"/>
		</colgroup>
		<thead>
			<tr>
				<th class="thGrid"><ui:icon id="icnCheck" className="fa-check-square-o fa-lg" title="page.com.selectToDelete"/></th>
				<th class="thGrid sortable:alphanumeric"><mc:msg key="per0202.grid.personNumber"/></th>
				<th class="thGrid sortable:alphanumeric"><mc:msg key="per0202.grid.surname"/></th>
				<th class="thGrid sortable:alphanumeric"><mc:msg key="per0202.grid.firstName"/></th>
				<th class="thGrid"><mc:msg key="per0202.grid.personType"/></th>
				<th class="thGrid sortable:alphanumeric"><mc:msg key="per0202.grid.empOrg"/></th>
				<th class="thGrid"><mc:msg key="per0202.grid.payslipEmail"/></th>
				<th class="thGrid"><mc:msg key="per0202.grid.mobile"/></th>
				<th class="thGrid"><mc:msg key="page.com.action"/></th>
			</tr>
		</thead>
		<tbody id="tblGridBody">
			<tr>
				<td class="tdGrid Ct" colspan="9"><mc:msg key="I002"/></td>
			</tr>
		</tbody>
	</table>
</div>
<div id="divPagingArea" class="areaContainerFrame"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>