/**************************************************************************************************
 * project
 * Description - SysMenuAuth - Menu Authority Group
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sys.sysAdmin.sysMenuAuth;

import zebra.data.ParamEntity;

public interface SysMenuAuthBiz {
	public ParamEntity getDefault(ParamEntity paramEntity) throws Exception;
	public ParamEntity getList(ParamEntity paramEntity) throws Exception;
	public ParamEntity exeInsert(ParamEntity paramEntity) throws Exception;
}