/**************************************************************************************************
 * project
 * Description - SysMenuAuth - Menu Authority Group
 *	- Generated by Source Generator
 *************************************************************************************************/
package project.app.sys.sysAdmin.sysMenuAuth;

import org.springframework.beans.factory.annotation.Autowired;

import project.common.extend.BaseAction;
import project.common.module.menu.MenuManager;

public class SysMenuAuthAction extends BaseAction {
	@Autowired
	private SysMenuAuthBiz biz;

	public String getDefault() throws Exception {
		biz.getDefault(paramEntity);
		return "list";
	}

	public String getList() throws Exception {
		biz.getList(paramEntity);
		return "list";
	}

	public String exeInsert() throws Exception {
		try {
			biz.exeInsert(paramEntity);
			MenuManager.reload();
		} catch (Exception ex) {
		}
		setRequestAttribute("paramEntity", paramEntity);
		return "ajaxResponse";
	}
}