<%/************************************************************************************************
* Description - PerBasicProfile - Person Profile (Old Type)
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	DataSet dsRequest = (DataSet)paramEntity.getRequestDataSet();
	String personId = dsRequest.getValue("personId");
	String assignmentId = dsRequest.getValue("assignmentId");
	HpPersonD person = (HpPersonD)session.getAttribute("HpPersonDQuickSearch");
	DataSet dsPerson = (DataSet)paramEntity.getObject("dsPerson");
	DataSet dsAsg = (DataSet)paramEntity.getObject("dsAsg");
	DataSet dsPrt = (DataSet)paramEntity.getObject("dsPrt");
	DataSet timesheetApprovers = (DataSet)paramEntity.getObject("timesheetApprovers");
	DataSet timesheetNotiOrg = (DataSet)paramEntity.getObject("dsNotiOrg");
	DataSet expenseApprovers = (DataSet)paramEntity.getObject("expenseApprovers");
	DataSet expenseNotiOrg = (DataSet)paramEntity.getObject("dsNotiOrg");
	DataSet deliverableApprovers = (DataSet)paramEntity.getObject("deliverableApprovers");
	DataSet deliverableNotiOrg = (DataSet)paramEntity.getObject("dsNotiOrg");
	String timesheetApprover1Id = dsAsg.getValue("TIMECARD_APPROVAL_ID");
	String timesheetApprover2Id = dsAsg.getValue("TIMECARD_SECONDARY_APPROVAL_ID");
	String timesheetApprover3Id = dsAsg.getValue("TIMECARD_TERTIARY_APPROVAL_ID");
	String timesheetNotiToOrgId = dsAsg.getValue("TIMESHEET_NOTI_ORG_ID");
	String expenseApprover1Id = dsAsg.getValue("EXPENSE_APPROVER_1");
	String expenseApprover2Id = dsAsg.getValue("EXPENSE_APPROVER_2");
	String expenseApprover3Id = dsAsg.getValue("EXPENSE_APPROVER_3");
	String expenseNotiToOrgId = dsAsg.getValue("EXPENSE_APPROVAL_NOTI_TO_ORG");
	String deliverableApprover1Id = dsAsg.getValue("DELIVERABLES_APPROVER_1");
	String deliverableApprover2Id = dsAsg.getValue("DELIVERABLES_APPROVER_2");
	String deliverableApprover3Id = dsAsg.getValue("DELIVERABLES_APPROVER_3");
	String deliverableNotiToOrgId = dsAsg.getValue("DELIVERABLES_APPR_NOTI_TO_ORG");
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconPerci.png">
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
/* button.bootstrapSelect.dropdown-toggle {padding:3px 20px 2px 5px;} */
/* .tblEdit th {padding:2px 4px;} */
/* .tblEdit td {padding:2px 2px;} */
/* .tblGrid th, .tblGrid td {padding:5px 4px;} */
/* .thEdit {padding:2px 4px;} */
/* .tdEdit {padding:2px 2px;} */
/* .txtEn, .txtDpl, .txtDis, .txaEn, .txaDis, .txaDpl {padding:4px 4px;} */
/* .btn {padding:2px 10px;} */
/* .sectionHeader {padding:2px 4px;background:#f5f5f5;border:1px solid #dddddd} */
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
var personId = "<%=personId%>";
var assignmentId = "<%=assignmentId%>";
var prtDocumentId = "<%=dsPrt.getValue("PRT_DOCUMENT_ID")%>";
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body class="bodyFrame">
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divFrameWindowHolder">
<div id="divFixedPanelFrame">
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainerFrame">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnSave" caption="button.com.save"/>
			<ui:button id="btnCreateExtensionOpp" caption="Create Extension Opportunity" iconClass="fa-plus-square"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea">
</div>
<div id="divInformArea" class="areaContainerFrame">
	<div id="divPersonHeader" class="alert alert-info personInfoHeader"><%=person.getFullName()%> (<%=person.getPersonNumber()%>) <%=person.getPersonType()%></div>
</div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanelFrame">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainerFrame">
	<div id="divFrameDataAreaWrapper">
		<div class="accordion" style="width:35%;float:left">
			<div class="accordionGroup">
				<h3>Assignment Detail</h3>
				<div id="divAsgDetail" class="accordionContents">
					<table id="tblAsgDetail" class="tblEdit">
						<colgroup>
							<col width="25%"/>
							<col width="*"/>
						</colgroup>
						<tbody>
							<tr>
								<th class="thEdit rt mandatory">Asg Status</th>
								<td class="tdEdit">
									<ui:check name="asgPreferred" value="Y" text="Preferred" isChecked="<%=dsAsg.getValue(\"PREFERRED\")%>" isCustomised="true"/>
									<ui:check name="asgActive" value="Y" text="Active" isChecked="<%=dsAsg.getValue(\"ASG_ACTIVE\")%>" isCustomised="true"/>
								</td>
							</tr>
							<tr>
								<th class="thEdit rt mandatory">Asg Date</th>
								<td class="tdEdit">
									<ui:text name="asgStartDate" className="Ct hor" value="<%=dsAsg.getValue(\"ASG_START_DATE_FORMAT\")%>" style="width:90px" options="mandatory" option="date"/><ui:icon id="icnAsgStartDate" className="fa-calendar hor"/>
									<div class="horGap10" style="padding:6px 6px 0px 0px;">-</div>
									<ui:text name="asgEndDate" className="Ct hor" value="<%=dsAsg.getValue(\"ASG_END_DATE_FORMAT\")%>" style="width:90px" options="mandatory" option="date"/><ui:icon id="icnAsgEndDate" className="fa-calendar hor"/>
								</td>
							</tr>
							<tr>
								<th class="thEdit rt">Asg Number</th>
								<td class="tdEdit"><ui:text name="asgNumber" className="Lt" value="<%=dsAsg.getValue(\"ASSIGNMENT_NUMBER\")%>" status="display"/></td>
							</tr>
							<tr>
								<th class="thEdit rt mandatory">Billing Org</th>
								<td class="tdEdit">
									<ui:text name="asgBillingOrgName" className="Lt" value="<%=dsAsg.getValue(\"BILLING_ORGANISATION_NAME\")%>" options="mandatory" checkName="Billing Organisation"/>
									<ui:hidden name="asgBillingOrgId" value="<%=dsAsg.getValue(\"BILLING_ORGANISATION_ID\")%>"/>
								</td>
							</tr>
							<tr>
								<th class="thEdit rt mandatory">Billing Org Contact</th>
								<td class="tdEdit">
									<ui:text name="asgBillingOrgContactName" className="Lt" value="<%=dsAsg.getValue(\"BILLING_ORG_PERSON_NAME\")%>" options="mandatory" checkName="Billing Organisation Contact Person"/>
									<ui:hidden name="asgBillingOrgContactId" value="<%=dsAsg.getValue(\"BILLING_ORGANISATION_PERSON_ID\")%>"/>
								</td>
							</tr>
							<tr>
								<th class="thEdit rt mandatory">End User Org</th>
								<td class="tdEdit">
									<ui:text name="asgEuOrgName" className="Lt" value="<%=dsAsg.getValue(\"EU_ORGANISATION_NAME\")%>" options="mandatory" checkName="End User Organisation"/>
									<ui:hidden name="asgEuOrgId" value="<%=dsAsg.getValue(\"EU_ORGANISATION_ID\")%>"/>
								</td>
							</tr>
							<tr>
								<th class="thEdit rt">End User Org Contact</th>
								<td class="tdEdit">
									<ui:text name="asgEuOrgContactName" className="Lt" value="<%=dsAsg.getValue(\"EU_ORG_PERSON_NAME\")%>"/>
									<ui:hidden name="asgEuOrgContactId" value="<%=dsAsg.getValue(\"EU_CONTACT_PERSON_ID\")%>"/>
								</td>
							</tr>
							<tr>
								<th class="thEdit rt">Agency 2</th>
								<td class="tdEdit">
									<ui:text name="asgReferenceNo3Name" className="Lt" value="<%=dsAsg.getValue(\"REFERENCE_NO_3_NAME\")%>"/>
									<ui:hidden name="asgReferenceNo3Id" value="<%=dsAsg.getValue(\"REFERENCE_NO_3\")%>"/>
								</td>
							</tr>
							<tr>
								<th class="thEdit rt">Agency Margin Org</th>
								<td class="tdEdit">
									<ui:text name="asgReferenceNo2Name" className="Lt" value="<%=dsAsg.getValue(\"REFERENCE_NO_2_NAME\")%>"/>
									<ui:hidden name="asgReferenceNo2Id" value="<%=dsAsg.getValue(\"REFERENCE_NO_2\")%>"/>
								</td>
							</tr>
							<tr>
								<th class="thEdit rt">Sales Org</th>
								<td class="tdEdit">
									<ui:text name="asgReferenceNo1Name" className="Lt" value="<%=dsAsg.getValue(\"REFERENCE_NO_1_NAME\")%>"/>
									<ui:hidden name="asgReferenceNo1Id" value="<%=dsAsg.getValue(\"REFERENCE_NO_1\")%>"/>
								</td>
							</tr>
							<tr>
								<th class="thEdit rt">Cost Centre</th>
								<td class="tdEdit"><ui:text name="asgCostCentre" className="Lt" value="<%=dsAsg.getValue(\"COST_CENTRE\")%>"/></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div class="accordionGroup">
				<h3>PRT / Workcover</h3>
				<div id="divPrtWorkcover" class="accordionContents" style="overflow:hidden;">
					<div class="divTabArea">
						<ui:tab id="tabPrtWorkcover">
							<ui:tabList caption="Payroll Tax" isActive="true" iconClass="fa-money" iconPosition="left" useAutoScript="false"/>
							<ui:tabList caption="Workcover" iconClass="fa-medkit" iconPosition="left" useAutoScript="false"/>
						</ui:tab>
					</div>
					<div id="divPrtWorkcover0" class="areaContainerFrame" style="padding:2px 0px 2px 0px;">
						<div class="divButtonArea sectionHeader">
							<div class="divButtonAreaRight">
								<ui:buttonGroup>
									<ui:button id="btnAddAsgPrt" caption="Add" iconClass="fa-plus"/>
								</ui:buttonGroup>
							</div>
						</div>
						<div class="verGap2"></div>
						<table id="tblAsgPrt" class="tblEdit">
							<colgroup>
								<col width="25%"/>
								<col width="*"/>
							</colgroup>
							<tbody>
								<tr>
									<th class="thEdit rt">Working State</th>
									<td class="tdEdit"><ui:text name="prtWorkingState" value="<%=dsPrt.getValue(\"PRT_WORKING_STATE_MEANING\")%>" status="display"/></td>
								</tr>
								<tr>
									<th class="thEdit rt">Liable</th>
									<td class="tdEdit"><ui:text name="prtLiable" value="<%=dsPrt.getValue(\"PRT_RESPONSIBLE_DESCRIPTION\")%>" status="display"/></td>
								</tr>
								<tr>
									<th class="thEdit rt">Percentage</th>
									<td class="tdEdit"><ui:text name="prtPercentage" value="<%=dsPrt.getValue(\"PRT_RATE\")%>" status="display"/></td>
								</tr>
								<tr>
									<th class="thEdit rt">Scenario</th>
									<td class="tdEdit"><ui:text name="prtScenario" value="<%=dsPrt.getValue(\"SCENARIO\")%>" status="display"/></td>
								</tr>
								<tr>
									<th class="thEdit rt">Created By</th>
									<td class="tdEdit"><ui:text name="prtCreatedByName" value="<%=dsPrt.getValue(\"CREATED_BY_NAME\")%>" status="display"/></td>
								</tr>
							</tbody>
						</table>
						<div class="verGap2"></div>
						<div id="divGridHolderPrtDocument" style="overflow:auto;">
							<table id="tblPrtDocument" class="tblGrid sort autosort" style="width:800px">
								<colgroup>
									<col width="*"></col>
									<col width="26%"></col>
									<col width="13%"></col>
									<col width="12%"></col>
								</colgroup>
								<thead>
									<tr>
										<th class="thGrid">Document Name</th>
										<th class="thGrid">Created By</th>
										<th class="thGrid">Creation Date</th>
										<th class="thGrid">Expiry Date</th>
									</tr>
								</thead>
								<tbody id="tbodyPrtDocument">
									<tr>
										<td class="tdGrid Ct" colspan="4"><mc:msg key="I001"/></td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
					<div id="divPrtWorkcover1" class="areaContainerFrame" style="padding:2px 0px 2px 0px;display:none;">
						<div class="divButtonArea sectionHeader">
							<div class="divButtonAreaRight">
								<ui:buttonGroup>
									<ui:button id="btnEditAsgWorkcover" caption="Edit" iconClass="fa-edit"/>
								</ui:buttonGroup>
							</div>
						</div>
						<div class="verGap2"></div>
						<table id="tblAsgWorkcover" class="tblEdit">
							<colgroup>
								<col width="25%"/>
								<col width="*"/>
							</colgroup>
							<tbody>
								<tr>
									<th class="thEdit rt">Working State</th>
									<td class="tdEdit"><ui:text name="wcWorkingState" value="<%=dsAsg.getValue(\"WC_WORKING_STATE_MEANING\")%>" status="display"/></td>
								</tr>
								<tr>
									<th class="thEdit rt">Code</th>
									<td class="tdEdit"><ui:text name="wcCodeName" value="<%=dsAsg.getValue(\"WC_CODE_RATE_NAME\")%>" status="display"/></td>
								</tr>
								<tr>
									<th class="thEdit rt">WIC / ANZIC</th>
									<td class="tdEdit"><ui:text name="wcWicAnzic" value="<%=dsAsg.getValue(\"WC_WIC_ANZIC\")%>" status="display"/></td>
								</tr>
								<tr>
									<th class="thEdit rt">Percentage</th>
									<td class="tdEdit"><ui:text name="wcPercentage" value="<%=dsAsg.getValue(\"WC_PERCENTAGE\")%>" status="display"/></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
			<div class="accordionGroup">
				<h3>Payroll / Invoice</h3>
				<div id="divPayrollInvoice" class="accordionContents">
					<table id="tblPayrollInvoice" class="tblEdit">
						<colgroup>
							<col width="25%"/>
							<col width="*"/>
						</colgroup>
						<tbody>
							<tr>
								<th class="thEdit rt">Billing Code</th>
								<td class="tdEdit">
									<ui:text name="asgBillingCodeName" value="<%=dsAsg.getValue(\"BILLING_CODE\")%>"/>
									<ui:hidden name="asgBillingCodeId" value="<%=dsAsg.getValue(\"BILLING_CODE_ID\")%>"/>
								</td>
							</tr>
							<tr>
								<th class="thEdit rt mandatory">Payment Method</th>
								<td class="tdEdit">
									<ui:text name="asgPaymentMethodName" value="<%=dsAsg.getValue(\"PAYMENT_METHOD_NAME\")%>"/>
									<ui:hidden name="asgPaymentMethodId" value="<%=dsAsg.getValue(\"PAY_METHOD_NAME\")%>"/>
								</td>
							</tr>
							<tr>
								<th class="thEdit rt">Payroll Notes</th>
								<td class="tdEdit"><ui:txa name="asgPayrollNotes" style="height:40px" value="<%=dsAsg.getValue(\"PAYROLL_NOTES\")%>"/></td>
							</tr>
							<tr>
								<th class="thEdit rt">Invoice Comments</th>
								<td class="tdEdit"><ui:txa name="asgComments" style="height:40px" value="<%=dsAsg.getValue(\"COMMENTS\")%>"/></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div class="accordionGroup">
				<h3>Assignment References</h3>
				<div id="divAsgReference" class="accordionContents">
					<table id="tblAsgReference" class="tblEdit">
						<colgroup>
							<col width="25%"/>
							<col width="*"/>
						</colgroup>
						<tbody>
							<tr>
								<th class="thEdit rt">Reference A(PO)</th>
								<td class="tdEdit"><ui:text name="asgReferenceA" value="<%=dsAsg.getValue(\"REFERENCE_A_PO\")%>"/></td>
							</tr>
							<tr>
								<th class="thEdit rt">Reference B</th>
								<td class="tdEdit"><ui:text name="asgReferenceB" value="<%=dsAsg.getValue(\"REFERENCE_B\")%>"/></td>
							</tr>
							<tr>
								<th class="thEdit rt">Reference C</th>
								<td class="tdEdit"><ui:text name="asgReferenceC" value="<%=dsAsg.getValue(\"REFERENCE_C\")%>"/></td>
							</tr>
							<tr>
								<th class="thEdit rt">Reference D</th>
								<td class="tdEdit"><ui:text name="asgReferenceD" value="<%=dsAsg.getValue(\"REFERENCE_D\")%>"/></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="accordion" style="width:64%;float:right">
			<div class="accordionGroup">
				<h3>Asg Rates</h3>
				<div id="divAsgRate" class="accordionContents">
					<div class="divButtonArea sectionHeader">
						<div class="divButtonAreaRight">
							<ui:buttonGroup>
								<ui:button id="btnAddAsgRate" caption="Add" iconClass="fa-plus"/>
							</ui:buttonGroup>
						</div>
					</div>
					<div class="verGap2"></div>
					<div id="divGridHolderAsgRates" style="overflow:auto">
						<table id="tblAsgRates" class="tblGrid sort autosort" style="width:1800px">
							<colgroup>
								<col width="3%"></col>
								<col width="5%"></col>
								<col width="5%"></col>
								<col width="4%"></col>
								<col width="13%"></col>
								<col width="*"></col>
								<col width="6%"></col>
								<col width="7%"></col>
								<col width="6%"></col>
								<col width="7%"></col>
								<col width="6%"></col>
								<col width="7%"></col>
								<col width="5%"></col>
								<col width="6%"></col>
							</colgroup>
							<thead>
								<tr>
									<th class="thGrid"><ui:icon useFor="actionHeaderGrid"/></th>
									<th class="thGrid">Pay Rate</th>
									<th class="thGrid">Period</th>
									<th class="thGrid">Units</th>
									<th class="thGrid">Element</th>
									<th class="thGrid">Alternate Name</th>
									<th class="thGrid">Charge Rate</th>
									<th class="thGrid">Charge Period</th>
									<th class="thGrid">Is Preferred</th>
									<th class="thGrid">Disp Timesheet</th>
									<th class="thGrid">Disp Expense</th>
									<th class="thGrid">Tax Percentage</th>
									<th class="thGrid">Has GST</th>
									<th class="thGrid">Is Recurring</th>
								</tr>
							</thead>
							<tbody id="tbodyAsgRates">
								<tr>
									<td class="tdGrid Ct" colspan="14"><mc:msg key="I001"/></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
			<div class="accordionGroup">
				<h3>Timesheets / Expenses / Deliverables</h3>
				<div id="divTsExpDeli" class="accordionContents">
					<div class="divTabArea">
						<ui:tab id="tabTsExpDeli">
							<ui:tabList caption="Timesheets" isActive="true" iconClass="fa-address-card" iconPosition="left" useAutoScript="false"/>
							<ui:tabList caption="Expenses" iconClass="fa-automobile" iconPosition="left" useAutoScript="false"/>
							<ui:tabList caption="Deliverables" iconClass="fa-credit-card" iconPosition="left" useAutoScript="false"/>
						</ui:tab>
					</div>
					<div id="divTsExpDeli0" class="areaContainerFrame" style="padding:2px 0px 2px 0px;">
						<div class="sectionHeader" style="padding:4px 4px;">
							<ui:check name="useTimesheet" value="Y" text="Use Timesheet" isChecked="<%=dsAsg.getValue(\"ATTRIBUTE10\")%>" isCustomised="true"/>
						</div>
						<div id="divTimesheetD">
							<div class="verGap2"></div>
							<table id="tblTimesheetD" class="tblEdit">
								<colgroup>
									<col width="14%"/>
									<col width="27%"/>
									<col width="6%"/>
									<col width="24%"/>
									<col width="*"/>
								</colgroup>
								<tbody>
									<tr>
										<th class="thEdit rt">Timesheet Name</th>
										<td class="tdEdit"><ui:text name="timesheetName" value="<%=dsAsg.getValue(\"TIMESHEET_NAME\")%>"/></td>
										<th class="thEdit rt">Units</th>
										<td class="tdEdit"><ui:ccselect name="timesheetUnits" codeType="TIMESHEET_UNIT" selectedValue="<%=dsAsg.getValue(\"TIMESHEET_UNITS\")%>" attribute="data-width:100%"/></td>
										<td class="tdEdit"><ui:check name="timesheetBulkApproval" value="Y" text="Enable Bulk Approval" isChecked="<%=dsAsg.getValue(\"IS_BULK_APPROVAL\")%>" isCustomised="true"/></td>
									</tr>
									<tr>
										<th class="thEdit rt">Primary Approver</th>
										<td class="tdEdit" colspan="3"><%=timesheetApprovers.getAsHtmlStringForSelectbox("PERSON_ID", "FULL_NAME", timesheetApprover1Id, "==Select==", "id:timsheetApprover1;name:timsheetApprover1;class:bootstrapSelect")%></td>
										<td class="tdEdit"><ui:text name="timesheetApprover1Email" value="<%=dsAsg.getValue(\"TIMESHEET_APPROVER_1_EMAIL\")%>" status="display"/></td>
									</tr>
									<tr>
										<th class="thEdit rt">Secondary Approver</th>
										<td class="tdEdit" colspan="3"><%=timesheetApprovers.getAsHtmlStringForSelectbox("PERSON_ID", "FULL_NAME", timesheetApprover2Id, "==Select==", "id:timsheetApprover2;name:timsheetApprover2;class:bootstrapSelect")%></td>
										<td class="tdEdit"><ui:text name="timesheetApprover2Email" value="<%=dsAsg.getValue(\"TIMESHEET_APPROVER_2_EMAIL\")%>" status="display"/></td>
									</tr>
									<tr>
										<th class="thEdit rt">Tertiary Approver</th>
										<td class="tdEdit" colspan="3"><%=timesheetApprovers.getAsHtmlStringForSelectbox("PERSON_ID", "FULL_NAME", timesheetApprover3Id, "==Select==", "id:timsheetApprover3;name:timsheetApprover3;class:bootstrapSelect")%></td>
										<td class="tdEdit"><ui:text name="timesheetApprover3Email" value="<%=dsAsg.getValue(\"TIMESHEET_APPROVER_3_EMAIL\")%>" status="display"/></td>
									</tr>
									<tr>
										<th class="thEdit rt">Send Notification To</th>
										<td class="tdEdit"><%=timesheetNotiOrg.getAsHtmlStringForSelectbox("ORGANISATION_ID", "ORGANISATION_NAME", timesheetNotiToOrgId, "==Select==", "id:timsheetNotiToOrg;name:timsheetNotiToOrg;class:bootstrapSelect;data-width:100%")%></td>
										<td class="tdEdit" colspan="2"><ui:select name="timesheetNotiToPerson" className="dropup" attribute="data-width:100%;data-dropup-auto:false"><ui:seloption value="" text="==Select=="/></ui:select></td>
										<td class="tdEdit"><ui:text name="timesheetNotiToPersonEmail" value="<%=dsAsg.getValue(\"TIMESHEET_NOTI_TO_EMAIL\")%>" status="display"/></td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
					<div id="divTsExpDeli1" class="areaContainerFrame" style="padding:2px 0px 2px 0px;display:none;">
						<div class="sectionHeader" style="padding:4px 4px;">
							<ui:check name="useExpense" value="Y" text="Use Expense" isChecked="<%=dsAsg.getValue(\"USE_EXPENSE\")%>" isCustomised="true"/>
						</div>
						<div id="divExpenseD">
							<div class="verGap2"></div>
							<table id="tblExpenseD" class="tblEdit">
								<colgroup>
									<col width="14%"/>
									<col width="27%"/>
									<col width="6%"/>
									<col width="24%"/>
									<col width="*"/>
								</colgroup>
								<tbody>
									<tr>
										<th class="thEdit rt">Expense Name</th>
										<td class="tdEdit" colspan="2"><ui:text name="expenseName" value="<%=dsAsg.getValue(\"EXPENSE_NAME\")%>"/></td>
										<td class="tdEdit" colspan="2"><ui:check name="expenseBulkApproval" value="Y" text="Enable Bulk Approval" isChecked="<%=dsAsg.getValue(\"IS_BULK_APPROVAL_EXPENSE\")%>" isCustomised="true"/></td>
									</tr>
									<tr>
										<th class="thEdit rt">Primary Approver</th>
										<td class="tdEdit" colspan="3"><%=expenseApprovers.getAsHtmlStringForSelectbox("PERSON_ID", "FULL_NAME", expenseApprover1Id, "==Select==", "id:expenseApprover1;name:expenseApprover1;class:bootstrapSelect")%></td>
										<td class="tdEdit"><ui:text name="expenseApprover1Email" value="<%=dsAsg.getValue(\"EXPENSE_APPROVER_1_EMAIL\")%>" status="display"/></td>
									</tr>
									<tr>
										<th class="thEdit rt">Secondary Approver</th>
										<td class="tdEdit" colspan="3"><%=expenseApprovers.getAsHtmlStringForSelectbox("PERSON_ID", "FULL_NAME", expenseApprover2Id, "==Select==", "id:expenseApprover2;name:expenseApprover2;class:bootstrapSelect")%></td>
										<td class="tdEdit"><ui:text name="expenseApprover2Email" value="<%=dsAsg.getValue(\"EXPENSE_APPROVER_2_EMAIL\")%>" status="display"/></td>
									</tr>
									<tr>
										<th class="thEdit rt">Tertiary Approver</th>
										<td class="tdEdit" colspan="3"><%=expenseApprovers.getAsHtmlStringForSelectbox("PERSON_ID", "FULL_NAME", expenseApprover3Id, "==Select==", "id:expenseApprover3;name:expenseApprover3;class:bootstrapSelect")%></td>
										<td class="tdEdit"><ui:text name="expenseApprover3Email" value="<%=dsAsg.getValue(\"EXPENSE_APPROVER_3_EMAIL\")%>" status="display"/></td>
									</tr>
									<tr>
										<th class="thEdit rt">Send Notification To</th>
										<td class="tdEdit"><%=expenseNotiOrg.getAsHtmlStringForSelectbox("ORGANISATION_ID", "ORGANISATION_NAME", expenseNotiToOrgId, "==Select==", "id:expenseNotiToOrg;name:expenseNotiToOrg;class:bootstrapSelect;data-width:100%")%></td>
										<td class="tdEdit" colspan="2"><ui:select name="expenseNotiToPerson" className="dropup" attribute="data-width:100%;data-dropup-auto:false"><ui:seloption value="" text="==Select=="/></ui:select></td>
										<td class="tdEdit"><ui:text name="expenseNotiToPersonEmail" value="<%=dsAsg.getValue(\"EXPENSE_NOTI_TO_EMAIL\")%>" status="display"/></td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
					<div id="divTsExpDeli2" class="areaContainerFrame" style="padding:2px 0px 2px 0px;display:none;">
						<div class="sectionHeader" style="padding:4px 4px;">
							<ui:check name="useDeliverable" value="Y" text="Use Deliverable" isChecked="<%=dsAsg.getValue(\"USE_DELIVERABLES\")%>" isCustomised="true"/>
						</div>
						<div id="divDeliverableD">
							<div class="verGap2"></div>
							<table id="tblDeliverableD" class="tblEdit">
								<colgroup>
									<col width="14%"/>
									<col width="27%"/>
									<col width="6%"/>
									<col width="24%"/>
									<col width="*"/>
								</colgroup>
								<tbody>
									<tr>
										<th class="thEdit rt">Deliverables Name</th>
										<td class="tdEdit" colspan="2"><ui:text name="deliverableName" value="<%=dsAsg.getValue(\"DELIVERABLES_NAME\")%>"/></td>
										<td class="tdEdit" colspan="2"><ui:check name="deliverableBulkApproval" value="Y" text="Enable Bulk Approval" isChecked="<%=dsAsg.getValue(\"IS_BULK_APPROVAL_DELIVERABLES\")%>" isCustomised="true"/></td>
									</tr>
									<tr>
										<th class="thEdit rt">Primary Approver</th>
										<td class="tdEdit" colspan="3"><%=deliverableApprovers.getAsHtmlStringForSelectbox("PERSON_ID", "FULL_NAME", deliverableApprover1Id, "==Select==", "id:deliverableApprover1;name:deliverableApprover1;class:bootstrapSelect")%></td>
										<td class="tdEdit"><ui:text name="deliverableApprover1Email" value="<%=dsAsg.getValue(\"DELIVERABLES_APPROVER_1_EMAIL\")%>" status="display"/></td>
									</tr>
									<tr>
										<th class="thEdit rt">Secondary Approver</th>
										<td class="tdEdit" colspan="3"><%=deliverableApprovers.getAsHtmlStringForSelectbox("PERSON_ID", "FULL_NAME", deliverableApprover2Id, "==Select==", "id:deliverableApprover2;name:deliverableApprover2;class:bootstrapSelect")%></td>
										<td class="tdEdit"><ui:text name="deliverableApprover2Email" value="<%=dsAsg.getValue(\"DELIVERABLES_APPROVER_2_EMAIL\")%>" status="display"/></td>
									</tr>
									<tr>
										<th class="thEdit rt">Tertiary Approver</th>
										<td class="tdEdit" colspan="3"><%=deliverableApprovers.getAsHtmlStringForSelectbox("PERSON_ID", "FULL_NAME", deliverableApprover3Id, "==Select==", "id:deliverableApprover3;name:deliverableApprover3;class:bootstrapSelect")%></td>
										<td class="tdEdit"><ui:text name="deliverableApprover3Email" value="<%=dsAsg.getValue(\"DELIVERABLES_APPROVER_3_EMAIL\")%>" status="display"/></td>
									</tr>
									<tr>
										<th class="thEdit rt">Send Notification To</th>
										<td class="tdEdit"><%=deliverableNotiOrg.getAsHtmlStringForSelectbox("ORGANISATION_ID", "ORGANISATION_NAME", deliverableNotiToOrgId, "==Select==", "id:deliverableNotiToOrg;name:deliverableNotiToOrg;class:bootstrapSelect;data-width:100%")%></td>
										<td class="tdEdit" colspan="2"><ui:select name="deliverableNotiToPerson" className="dropup" attribute="data-width:100%;data-dropup-auto:false"><ui:seloption value="" text="==Select=="/></ui:select></td>
										<td class="tdEdit"><ui:text name="deliverableNotiToPersonEmail" value="<%=dsAsg.getValue(\"DELIVERABLES_NOTI_TO_EMAIL\")%>" status="display"/></td>
									</tr>
								</tbody>
							</table>
							<div class="verGap4"></div>
							<div class="divButtonArea sectionHeader">
								<div class="divButtonAreaRight">
									<ui:buttonGroup>
										<ui:button id="btnAddDeliverableRate" caption="Add" iconClass="fa-plus"/>
									</ui:buttonGroup>
								</div>
							</div>
							<div class="verGap2"></div>
							<div id="divGridHolderDeliverableRate" style="overflow:auto;">
								<table id="tblDeliverableRate" class="tblGrid sort autosort" style="width:1300px">
									<colgroup>
										<col width="3%"></col>
										<col width="14%"></col>
										<col width="17%"></col>
										<col width="*"></col>
										<col width="8%"></col>
										<col width="8%"></col>
										<col width="10%"></col>
										<col width="12%"></col>
									</colgroup>
									<thead>
										<tr>
											<th class="thGrid"><ui:icon useFor="actionHeaderGrid"/></th>
											<th class="thGrid">Element</th>
											<th class="thGrid">Alternate Name</th>
											<th class="thGrid">Description</th>
											<th class="thGrid">Pay Rate</th>
											<th class="thGrid">Due Date</th>
											<th class="thGrid">Disp Deliverables</th>
											<th class="thGrid">Status</th>
										</tr>
									</thead>
									<tbody id="tbodyDeliverableRate">
										<tr>
											<td class="tdGrid Ct" colspan="8"><mc:msg key="I001"/></td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="accordionGroup">
				<h3>Invoice Allocation</h3>
				<div id="divInvoiceAllocation" class="accordionContents">
					<table id="tblInvoiceAllocation" class="tblEdit">
						<colgroup>
							<col width="20%"/>
							<col width="22%"/>
							<col width="13%"/>
							<col width="14%"/>
							<col width="13%"/>
							<col width="*"/>
						</colgroup>
						<tbody>
							<tr>
								<th class="thEdit rt">Invoice Template</th>
								<td class="tdEdit"><ui:text name="invoiceTemplate" value="<%=dsAsg.getValue(\"INVOICE_TEMPLATE\")%>" status="display"/></td>
								<th class="thEdit rt">Rate Type</th>
								<td class="tdEdit"><ui:text name="rateType" value="<%=dsAsg.getValue(\"UNIT_MEANING\")%>" status="display"/></td>
								<th class="thEdit rt">Last Invoice</th>
								<td class="tdEdit"><ui:text name="lastInvoiceDate" value="<%=dsAsg.getValue(\"LAST_INVOICE_DATE_FORMAT\")%>" status="display"/></td>
							</tr>
							<tr>
								<th class="thEdit rt">Payment Terms</th>
								<td class="tdEdit"><ui:text name="paymentTerms" value="<%=dsAsg.getValue(\"PAYMENT_TERMS\")%>" status="display"/></td>
								<th class="thEdit rt">Management Fee</th>
								<td class="tdEdit"><ui:text name="managementFee" value="<%=dsAsg.getValue(\"MANAGEMENT_FEE\")+\" %\"%>" status="display"/></td>
								<th class="thEdit rt">Last Paid</th>
								<td class="tdEdit"><ui:text name="lastPaidDate" value="<%=dsAsg.getValue(\"LAST_PAID_DATE_FORMAT\")%>" status="display"/></td>
							</tr>
							<tr>
								<th class="thEdit rt">Invoice Cycle</th>
								<td class="tdEdit"><ui:text name="invoiceCycle" value="<%=dsAsg.getValue(\"INVOICE_CYCLE_MEANING\")%>" status="display"/></td>
								<th class="thEdit rt">Payroll Tax</th>
								<td class="tdEdit"><ui:text name="payrollTax" value="<%=dsAsg.getValue(\"PAYROLL_TAX\")+\" %\"%>" status="display"/></td>
								<th class="thEdit rt">Next Invoice</th>
								<td class="tdEdit"><ui:text name="nextInvoiceDate" value="<%=dsAsg.getValue(\"NEXT_INVOICE_DATE_FORMAT\")%>" status="display"/></td>
							</tr>
							<tr>
								<th class="thEdit rt">Customer Support Consultant</th>
								<td class="tdEdit"><ui:text name="cscName" value="<%=dsAsg.getValue(\"CSC_NAME\")%>" status="display"/></td>
								<th class="thEdit rt"></th>
								<td class="tdEdit"></td>
								<th class="thEdit rt">Next Paid</th>
								<td class="tdEdit"><ui:text name="nextPaymentDate" value="<%=dsAsg.getValue(\"NEXT_PAYMENT_DATE_FORMAT\")%>" status="display"/></td>
							</tr>
							<tr>
								<th class="thEdit rt">Invoice Recipient Email</th>
								<td class="tdEdit" colspan="3"><ui:text name="invoiceRecipientEmail" value="<%=dsAsg.getValue(\"INVOICE_RECIPIENT_EMAIL\")%>"/></td>
								<th class="thEdit rt">Next Timesheet</th>
								<td class="tdEdit"><ui:text name="nextTimesheetDate" value="<%=dsAsg.getValue(\"NEXT_TIMESHEET_DATE_FORMAT\")%>" status="display"/></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
			<div class="accordionGroup">
				<h3>Contracts</h3>
				<div id="divContract" class="accordionContents">
					<table id="tblContract" class="tblEdit">
						<colgroup>
							<col width="10%"/>
							<col width="23%"/>
							<col width="10%"/>
							<col width="23%"/>
							<col width="10%"/>
							<col width="*"/>
						</colgroup>
						<tbody>
							<tr>
								<th class="thEdit rt">Start Time</th>
								<td class="tdEdit">
									<div style="float:left;padding-top:2px;"><ui:ccselect name="startTimeHour" selectedValue="<%=dsAsg.getValue(\"WORK_START_HH\")%>" caption="==Select==" codeType="HOUR_CODE" className="dropup" attribute="data-size:10;data-dropup-auto:false"/></div>
									<div style="float:left;padding:6px 6px 2px 6px;">:</div>
									<div style="float:left;padding-top:2px;"><ui:ccselect name="startTimeMin" selectedValue="<%=dsAsg.getValue(\"WORK_START_MM\")%>" caption="==Select==" codeType="MINUTE_CODE" className="dropup" attribute="data-size:10;data-dropup-auto:false"/></div>
								</td>
								<th class="thEdit rt">End Time</th>
								<td class="tdEdit">
									<div style="float:left;padding-top:2px;"><ui:ccselect name="endTimeHour" selectedValue="<%=dsAsg.getValue(\"WORK_END_HH\")%>" caption="==Select==" codeType="HOUR_CODE" className="dropup" attribute="data-size:10;data-dropup-auto:false"/></div>
									<div style="float:left;padding:6px 6px 2px 6px;">:</div>
									<div style="float:left;padding-top:2px;"><ui:ccselect name="endTimeMin" selectedValue="<%=dsAsg.getValue(\"WORK_END_MM\")%>" caption="==Select==" codeType="MINUTE_CODE" className="dropup" attribute="data-size:10;data-dropup-auto:false"/></div>
								</td>
								<th class="thEdit rt">Termination Notice</th>
								<td class="tdEdit">
									<div style="float:left;padding-top:2px;"><ui:ccselect name="terminationNotice" selectedValue="<%=dsAsg.getValue(\"TERMINATION_NOTICE\")%>" caption="==Select==" codeType="ASG_TERM_NOTICE" className="dropup" attribute="data-size:10;data-dropup-auto:false"/></div>
									<div style="float:left;padding:6px 6px 2px 6px;"></div>
									<div style="float:left;padding-top:2px;"><ui:ccselect name="terminationNoticeUnit" selectedValue="<%=dsAsg.getValue(\"TERMINATION_NOTICE_UNIT\")%>" caption="==Select==" codeType="ASG_TERM_NOTICE_UNIT"/></div>
								</td>
							</tr>
							<tr>
								<th class="thEdit rt">Equipment Required</th>
								<td class="tdEdit"><ui:ccradio name="equipmentRequired" codeType="SIMPLE_YN" selectedValue="<%=dsAsg.getValue(\"EQUIPMENT_REQUIRED_YN\")%>" isCustomised="true"/></td>
								<th class="thEdit rt" rowspan="2">Equipment</th>
								<td class="tdEdit" rowspan="2"><ui:txa id="equipment" name="equipment" value="<%=dsAsg.getValue(\"EQUIPMENT_DETAILS\")%>" style="height:46px;"/></td>
								<th class="thEdit rt" rowspan="2">Special Conditions</th>
								<td class="tdEdit" rowspan="2"><ui:txa id="specialConditions" name="specialConditions" value="<%=dsAsg.getValue(\"SPECIAL_CONDITIONS\")%>" style="height:46px;"/></td>
							</tr>
							<tr>
								<th class="thEdit rt mandatory">Job Title</th>
								<td class="tdEdit"><ui:text name="jobTitle" value="<%=dsAsg.getValue(\"JOB_TITLE\")%>" options="mandatory" checkName="Job Title"/></td>
							</tr>
							<tr>
								<th class="thEdit rt mandatory">Service Description</th>
								<td class="tdEdit"><ui:txa id="descriptionOfServices" name="descriptionOfServices" value="<%=dsAsg.getValue(\"SERVICE_DESCRIPTION\")%>" style="height:46px;"/></td>
								<th class="thEdit rt">Approved Expenses</th>
								<td class="tdEdit"><ui:txa id="approvedExpense" name="approvedExpense" value="<%=dsAsg.getValue(\"APPROVED_EXPENSES\")%>" style="height:46px;"/></td>
								<th class="thEdit rt">Restraint of Trade</th>
								<td class="tdEdit"><ui:txa id="restraintOfTrade" name="restraintOfTrade" value="<%=dsAsg.getValue(\"RESTRAINT_OF_TRADE\")%>" style="height:46px;"/></td>
							</tr>
							<tr>
								<th class="thEdit rt" rowspan="2">Work Location</th>
								<td class="tdEdit" rowspan="2"><ui:txa id="workLocation" name="workLocation" value="<%=dsAsg.getValue(\"ATTRIBUTE9\")%>" style="height:46px;"/></td>
								<th class="thEdit rt">Payment Arrangement</th>
								<td class="tdEdit"><ui:ccselect name="paymentArrangement" selectedValue="<%=dsAsg.getValue(\"PAYMENT_ARRANGMENT\")%>" caption="==Select==" codeType="PAYMENT_ARRANGMENT"/></td>
								<th class="thEdit rt"></th>
								<td class="tdEdit"></td>
							</tr>
							<tr>
								<th class="thEdit rt">&nbsp;</th>
								<td class="tdEdit"><ui:text name="dummy" status="display"/></td>
								<th class="thEdit rt">&nbsp;</th>
								<td class="tdEdit">&nbsp;</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="divPagingArea"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>