<%/************************************************************************************************
* Description - PerBasicProfile - Person Profile (Old Type)
*	- Generated by Source Generator
************************************************************************************************/%>
<%@ include file="/shared/page/incCommon.jsp"%>
<%/************************************************************************************************
* Declare objects & variables
************************************************************************************************/%>
<%
	ParamEntity paramEntity = (ParamEntity)request.getAttribute("paramEntity");
	HpPersonD hpPersonD = (HpPersonD)session.getAttribute("HpPersonDQuickSearch");
	String personId = "", personNumber = "", personNameToDisplay = "";
	if (hpPersonD != null) {
		personId = CommonUtil.toStringForId(hpPersonD.getPersonId());
		personNumber = hpPersonD.getPersonNumber();
		personNameToDisplay = hpPersonD.getFullName()+" ("+personNumber+")";
	}
%>
<%/************************************************************************************************
* HTML
************************************************************************************************/%>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<link rel="icon" type="image/png" href="<mc:cp key="imgIcon"/>/faviconPerci.png">
<title><mc:msg key="main.system.title"/></title>
<%/************************************************************************************************
* Stylesheet & Javascript
************************************************************************************************/%>
<%@ include file="/shared/page/incCssJs.jsp"%>
<style type="text/css">
</style>
<script type="text/javascript" src="<mc:cp key="viewPageJsName"/>"></script>
<script type="text/javascript">
</script>
</head>
<%/************************************************************************************************
* Page & Header
************************************************************************************************/%>
<body>
<form id="fmDefault" name="fmDefault" method="post" action="">
<div id="divHeaderHolder" class="ui-layout-north"><%@ include file="/project/common/include/header.jsp"%></div>
<div id="divBodyHolder" class="ui-layout-center">
<div id="divBodyLeft" class="ui-layout-west"><%@ include file="/project/common/include/bodyLeft.jsp"%></div>
<div id="divBodyCenter" class="ui-layout-center">
<div id="divFixedPanel">
<div id="divLocationPathArea"><%@ include file="/project/common/include/bodyLocationPathArea.jsp"%></div>
<%/************************************************************************************************
* Real Contents - fixed panel(tab, button, search, information)
************************************************************************************************/%>
<div id="divTabArea"></div>
<div id="divButtonArea" class="areaContainer">
	<div id="divButtonAreaLeft"></div>
	<div id="divButtonAreaRight">
		<ui:buttonGroup id="buttonGroup">
			<ui:button id="btnNew" caption="button.com.new"/>
			<ui:button id="btnSearch" caption="button.com.search"/>
			<ui:button id="btnClear" caption="button.com.clear"/>
			<ui:button id="btnExport" caption="button.com.export"/>
		</ui:buttonGroup>
	</div>
</div>
<div id="divSearchCriteriaArea" class="areaContainer">
	<table class="tblSearch">
		<caption><mc:msg key="page.com.searchCriteria"/></caption>
		<colgroup>
			<col width="8%"/>
			<col width="19%"/>
			<col width="6%"/>
			<col width="19%"/>
			<col width="7%"/>
			<col width="19%"/>
			<col width="7%"/>
			<col width="*"/>
		</colgroup>
		<tr>
			<th class="thSearch rt">Person equals</th>
			<td class="tdSearch"><ui:hidden name="personId" value="<%=personId%>"/><ui:text name="personEquals" value="<%=personNameToDisplay%>" style="width:95%"/></td>
			<th class="thSearch rt">Person like</th>
			<td class="tdSearch"><ui:text name="personLike" value="<%=personNumber%>" style="width:95%"/></td>
			<th class="thSearch rt">Person Id like</th>
			<td class="tdSearch"><ui:text name="personIdLike" style="width:95%"/></td>
			<th class="thSearch rt"></th>
			<td class="tdSearch"></td>
		</tr>
		<tr>
			<th class="thSearch rt">Emp. Organisation</th>
			<td class="tdSearch">
				<ui:hidden name="empOrgId"/>
				<ui:text name="empOrgName" className="hor" style="width:95%"/>
<%-- 				<ui:icon id="icnEmpOrgSearch" className="fa-search hor"/> --%>
			</td>
			<th class="thSearch rt">Person Type</th>
			<td class="tdSearch"><ui:ccselect name="personType" codeType="PERSON_TYPES" isMultiple="true" attribute="data-size:20;data-width:286px;"/></td>
			<th class="thSearch rt">Email</th>
			<td class="tdSearch"><ui:text name="email" style="width:95%"/></td>
			<th class="thSearch rt">Mobile Number</th>
			<td class="tdSearch"><ui:text name="mobile" style="width:100%"/></td>
		</tr>
	</table>
</div>
<div id="divInformArea"></div>
<%/************************************************************************************************
* End of fixed panel
************************************************************************************************/%>
<div class="breaker"></div>
</div>
<div id="divScrollablePanel">
<%/************************************************************************************************
* Real Contents - scrollable panel(data, paging)
************************************************************************************************/%>
<div id="divDataArea" class="areaContainer">
	<table id="tblGrid" class="tblGrid sort autosort">
		<colgroup>
			<col width="4%"/>
			<col width="13%"/>
			<col width="13%"/>
			<col width="*"/>
			<col width="21%"/>
			<col width="16%"/>
			<col width="5%"/>
			<col width="7%"/>
		</colgroup>
		<thead>
			<tr>
				<th class="thGrid">Number</th>
				<th class="thGrid sortable:alphanumeric">Surname</th>
				<th class="thGrid sortable:alphanumeric">First Name</th>
				<th class="thGrid">Person Type</th>
				<th class="thGrid sortable:alphanumeric">Employment Organisation</th>
				<th class="thGrid">Payslip Email</th>
				<th class="thGrid">No. of Asg</th>
				<th class="thGrid">Mobile Number</th>
			</tr>
		</thead>
		<tbody id="tblGridBody">
			<tr>
				<td class="tdGrid Ct" colspan="8"><mc:msg key="I002"/></td>
			</tr>
		</tbody>
	</table>
</div>
<div id="divPagingArea" class="areaContainer"></div>
<%/************************************************************************************************
* Right & Footer
************************************************************************************************/%>
</div>
</div>
<div id="divBodyRight" class="ui-layout-east"><%@ include file="/project/common/include/bodyRight.jsp"%></div>
</div>
<div id="divFooterHolder" class="ui-layout-south"><%@ include file="/project/common/include/footer.jsp"%></div>
<%/************************************************************************************************
* Additional Elements
************************************************************************************************/%>
</form>
<%/************************************************************************************************
* Additional Form
************************************************************************************************/%>
<form id="fmHidden" name="fmHidden" method="post" action=""></form>
</body>
</html>